### ISSUE TITLE
[validate][combobox] Validators do not work on Combobox

### ISSUE THREAD

**Issue by davidoff31** [ing-bank/lion#1018]
## Expected behavior

I should be able to apply at least a Required validator to a combobox

## Actual Behavior

When I set the .validators property on the combobox I get an error 

implementation
![image](https://user-images.githubusercontent.com/63789961/95575088-638eac00-0a2e-11eb-9499-1115755ce947.png)

error 

![image](https://user-images.githubusercontent.com/63789961/95575122-743f2200-0a2e-11eb-941d-da52d3a6535b.png)

## Additional context

As seen on Combobox v0.1.2

**Comment by jorenbroekema** [comment]
Yep, reproduced it, looking into a fix 👍  thanks for notifying

**Comment by davidoff31** [comment]
@jorenbroekema The problem is still present with version 0.1.3 :disappointed:

**Comment by jorenbroekema** [comment]
Hmm I spoke to Palash as well, apparently I solved a different bug (validation wasn't working with combobox, but I didn't get an error thrown).

The error you are seeing is quite common, it usually happens when you have multiple installs of @lion/form-core, so I would try to do:

```sh
npm ls @lion/form-core
```

And verify that there is only 1 install and the rest is deduped.

**Comment by davidoff31** [comment]
I did have conflicting versions of form-core indeed.
Unfortunately the problem is there even when I resolve them:
![image](https://user-images.githubusercontent.com/63789961/96605403-750d6900-12f6-11eb-9def-de77b40a89fb.png)

Implement this:
![image](https://user-images.githubusercontent.com/63789961/96605450-83f41b80-12f6-11eb-9f5b-e05a0c3de50a.png)

and I get these errors:
![image](https://user-images.githubusercontent.com/63789961/96605546-9ec69000-12f6-11eb-9803-aa60724ab7ab.png)

**Comment by jorenbroekema** [comment]
That's weird, npm should be able to dedupe the lion/form-core from the combobox up the tree to the lion/form-core in your root node modules, since they are the same version. The errors you get are expected if you have multiple installations, so that part is not really a bug on our end. 

Did you try:

```sh
npm dedupe
```

Or nuke your node_modules completely and reinstall?

**Comment by davidoff31** [comment]
That made the trick, thanks
