### ISSUE TITLE
[lion-switch] value within form is parsed in modelValue under "undefined" 

### ISSUE THREAD

**Issue by davidoff31** [ing-bank/lion#1058]
## Expected behavior

When lion-switch is used within form its value should be parsed in modelValue with the name as key. This happened until last release.

## Actual Behavior

The value is still parsed, but with key "undefined".

## Additional context

Looking at documentation doesn't seem as if the switch is expected to be used in forms, still if this is the case it should not pollute the form modelValue.

**Comment by tlouisse** [comment]
The switch is designed to work with and without form (just like every FormControl), so this is a 'valid bug' :)
For the switch it's just more likely to be used outside of the form, that's why it's in the Buttons section in docs.

It should actually be added to our 'umbrella form' here: https://lion-web-components.netlify.app/?path=/docs/forms-features-overview--main 

I will mark this as a bug, thanks for reporting.

**Comment by jorenbroekema** [comment]
Added it in the umbrella form demo in the PR mentioned above. I am not able to reproduce the bug there so I will assume it got fixed. If not, feel free to reopen with a reproduction
