### ISSUE TITLE
Select-rich in a dialog console error

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#1064]
## Expected behavior

No error in console

## Actual Behavior

1. Go to : https://lion-web-components.netlify.app/?path=/docs/forms-system-dialog-integrations--main
1.  Open devtools console

Error logged:
```
Error: Registration could not finish. Please use await el.registrationComplete
```

## Additional context

It seems to happen for nested overlays, the disconnectCallback is called before registration is complete for the components in the top overlay

**Comment by jorenbroekema** [comment]
Tough bug, either:
- the dialog needs to know about select rich and await registration before moving the content node in the DOM or
- we should *somehow* make sure that the content node is moved in the DOM before registration of nested nodes starts

First one is bad, because dialog should be agnostic about the content in the content node.

Second may be possible. You could try to delay the initialisation of registrationComplete promise to the connectedCallback, but I'm making the assumption here that because select rich is inside dialog content node, the select rich connected callback is only fired once (because it is moved to the global overlay container before it has a chance to connect). I'm not sure if it breaks other things by delaying this logic.. would need to explore it I think...

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/discussions/988 inspiration for a third option: delaying rendering the dialog content until it is opened. This is already possible, although requires a little work on the end user. Might be a good idea to document the solution we like best for this
