### ISSUE TITLE
Generate localize switch fallback for polymer-cli in a prepublish NPM script

### ISSUE THREAD

**Issue by bashmish** [ing-bank/lion#111]
Will we ever be able to resolve the FIXMEs? Would it maybe be an idea to autogenerate this switch statement as a prepublish script, so we keep the source code succinct and maintainable?

_Originally posted by @tlouisse in https://github.com/ing-bank/lion/issues/100#issuecomment-502554145_

**Comment by tlouisse** [comment]
Also discussed this with @dakMor and he agrees this would be a nice improvement to our code.

The prepublish script then can use `static get localizeNamespaces() { ... }` as a hook.

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
as a dedicated list like we have now is easier to handle by all bundler we decided to keep it in 👍

Therefore closing this feature request
