### ISSUE TITLE
Clarifications needed for creating a custom Tailwind version of LION.

### ISSUE THREAD

**Issue by mehdi-cit** [ing-bank/lion#1174]
Hello, 
The README suggests (among other things) the possibility of using this white-label web-components library together with tailwind for styling/customization.

 ... `you could use Lion to create a **web component version** of your favorite design systems, such as: ... **Tailwind**.`

Very interesting indeed!

However, from where I stand this is not possible. Let me try to explain:

Tailwind relies on setting classes on individual DOM elements (inline styling of sorts). So, in case of a "sophisticated" enough web component with elaborated "shadow- DOM". Tailwind way of styling would need us to drill down the shadow-DOM and "manually" set the class attribute of the inner DOM tags.

On the other hand. From your article and after quickly looking into the source code. Styling ING web component has to be done at the "top" of any given web-component. For instance, through using the lit-html css helper:
css` /* my custom stylings of this eb-component */ `;

Please clarify, have I missed something. Is there truly a way to marry ING white labeled component with Tailwind or was it just a miss-understanding from your part on how Tailwind works!

Thank you again!

**Comment by tlouisse** [comment]
Hey @mehdi-cit,

  I think it should be possible to style our components with Tailwind.
    Like you said, it is not possible to apply Tailwind classes on top of a component. 
    This is due to the nature of web-components: their interface abstracts away a complete html tree that lives in the shadow dom of the web component. So a `lion-input` creates a complete dom tree (comparable to the [html structure of Bootstrap](https://getbootstrap.com/docs/5.0/forms/validation/#custom-styles) for instance).   
    
How would you access this dom tree, then?    
    There would be several approaches possible, I will list them below.
    
###       1. Apply styles to the existing html structure
The basic idea behind Lion is that you create you own components by extending ours, so do the following:
       
```js
         import { css } from '@lion/core';
import { tailWindInputStyles } from './tailWindInputStyles.js';  

class TailwindInput extends LionInput {     
  static get styles() { 
    return [             
      // Option A: define inline             
      css`
        .form-field__label {
          /** your custom css here, but it would be hard to use preprocessors, so see below **/
        }
      `,             
       // Option B: import from external file
       tailWindInputStyles ,        
    ] ,
  }
}
```
 
   Since Tailwind exposes classes that you can apply to other selecttors via a [preprocessors](https://tailwindcss.com/docs/using-with-preprocessors) like PostCSS with @apply, you could do:  

_tailWindInputStyles.css_
```css
   .form-field__label {       
     @apply p-4 bg-white rounded; 
   } 
```
   
    However, we would need to write a PostCSS plugin to turn it into a CSSResult (this is what LitElement expects), so that it will output: 
    
_tailWindInputStyles.js _


```js
     import { css } from '@lion/core';
       
       export const tailWindInputStyles = css`   
         .form-field__label {       
           padding: 16px;        
           background-color: white;        
           border-radius: 4px;   
         }
        `;
```
        
### 2. Override html 
In this second approach, you apply the Tailwind classes in the html:

```js
           import { css } from '@lion/core';
import { tailWindClasses } from './tailWindClasses.js'  ;

class TailwindInput extends LionInput {     
  static get styles() {         
    return [
      ...([super.styles || []]),
         tailWindClasses ,
      ]     
   },      
    
    /**     
     * @override
     * @return {TemplateResult}
     */
    _labelTemplate() {
      return html‘
        <div class="form-field__label p-4 bg-white rounded">
          <slot name="label"></slot>
        </div>
      ‘;
    }
 } 
```





  I hope this example is straightforward, the only thing is that loading all tailWindClasses in every shadow root is not a good idea (although [Constructable stylesheets](https://dev.to/westbrook/why-would-anyone-use-constructible-stylesheets-anyways-19ng) probably mitigate performance impacts of loading so much css for many relatively small dom trees). 
  
  A better alternative could be to split up your classes in separate files and import only what you need.    Something like:

```js  
  import { twPadding, twBg, twBorder } from '@my-project/tw-utils/index.js';
  ...
  static get styles() {
   return [
    ...([super.styles || []]),
      twPadding, 
      twBg, 
      twBorder,
    ],
  }
  ...
```
  
#### Something to keep in mind when updating to latest Lion
  When you extend html, you need to be aware that templates can contain logic, accessibility etc, so you would have to take this into account whenever you update Lion (whether it breaks or you don't miss out on functionality or a11y). 
  A proposal to mitigate this is written down here: https://github.com/ing-bank/lion/discussions/591
  
  
  ### 3. Expose shadow parts (in the future)
This is something we don’t have yet, but we are looking for the best way to implement this at the moment. It would allow you to style our components in a way somewhat similar to solution 1, but without having to extend it.  See this proposal from @jorgecasar: https://dev.to/westbrook/why-would-anyone-use-constructible-stylesheets-anyways-19ng

We have not implemented this yet, because we need to decide:
- how to make it possible for extending parties to lock styling of the component
- whether we want to replace our current classes with parts (or have a directive that adds both) 
- align the implementation for all components throughout our codebase: normalize all html structures (do we start at host or one layer deeper, do we 'loosen up' our html structure to create more styling hooks etc.)
- how to handle global overlays (they loose their local context, since they are added to the body)

#### Something to keep in mind with this approach
For some components, you still might need to change html and thus extend our components. For instance with the Material Design input, you need to switch help-text from top to bottom (this - dom order following visual order - is a must have for a11y). For a floating label, dom structure changes are needed as well (see https://github.com/ing-bank/lion/blob/master/packages/combobox/docs/md-combobox/MdFieldMixin.js)
What you also need to keep in mind is that if you need to support IE, this won't be an option, unless there's a good polyfill.

### 4. Class mappings (in the future (?))

This is something that is not publicly exposed, but maybe could be in the future. The use case would be when you design your components in a 'traditional' way. So for instance you have an existing website using a BEM like structure for components, that are enhanced via Bootstrap. Your css files are your single source of truth with regard to html/css structure.

Some part of your site is rendered via a cms and uses the html structure as defined in your css, but some part needs to be mapped to our web components.

It would be possible to write a pre/post processor that allows you to use your original SSOT css files and map them to the selectors exposed by our components (so your `.my-input {}` would be mapped to `:host {}` of lion-input and your `my-input__helper-text` to `.form-field__help-text ::slotted(*)`.

**Comment by mehdi-cit** [comment]
Thank you for a detailed explanation. 
If one is fine with using @apply one can simply use something like a **webpack loader** that would "run" the @apply "thing" to turn tailwind class names to equivalent CSS. 
So in your very first code sample. You would remove any reference to anything called tailWindInputStyles. Instead, in the styles() function you'd simply have something like:

```
css`
        .form-field__label {
          @apply p-4 bg-white rounded;
        }
      `
```
The custom **webpack loader** would run on all **.js** files and look for the **@apply** key word. When it's encountered, it'd take that  **@apply p-4 bg-white rounded;** line and replace it with the execution of such line. I.e. it'd be replaced by the  **webpack loader** to become 
```
css`
        .form-field__label {
          padding: 16px;
          background-color: white; 
          border-radius: 4px;
        }
      `
```
However, this means the resulting DOM (as viewed in the devtools for instance would no longer be "Tailwindy"). So you'd be using tailwind when coding but not while debugging (which for me is a big loss, even using pre-processing is something I'd like to avoid in my specific use case).

PS: Never tried to use PostCSS from within a **webpack loader** but I cannot see why it'd not work!

**Comment by tlouisse** [comment]
> So in your very first code sample. You would remove any reference to anything called tailWindInputStyles. Instead, in the styles() function you'd simply have something like:

I figured that would be possible as well indeed, since it's also possible for React code. Didn't expect it to be easier then doing it in a distinct file. Whatever suits your needs I guess :)

If you want the debug experience, you should go for solution 2.
Then you basically use the approach as described here: https://tailwindcss.com/docs/extracting-components.

What you also can do is defining the html structure yourself:

```js
class TailwindInput extends LionInput {
  render() {
    return html`
      <div class="form-field__group-one">
        <div class="form-field__label">
          <slot name="label"></slot>
        </div>
        <small class="form-field__help-text">
          <slot name="help-text"></slot>
        </small>
      </div>
      <div class="form-field__group-two">
        <div class="input-group">
          <div class="input-group__before">
            <slot name="before"></slot>
          </div>
          <div class="input-group__container">
            <div class="input-group__prefix">
              <slot name="prefix"></slot>
            </div>
            <div class="input-group__input">
              <slot name="input"></slot>
            </div>
            <div class="input-group__suffix">
              <slot name="suffix"></slot>
            </div>
          </div>
          <div class="input-group__after">
            <slot name="after"></slot>
          </div>
        </div>
        <div class="form-field__feedback">
          <slot name="feedback"></slot>
        </div>
     </div>
    `;
  }
}
```

Instead of the classes here, you add the Tailwind classes.
Let us know if this would work for you 🙂

**Comment by mehdi-cit** [comment]
Thank you again!
I am putting this on hold for now and may come back to it later.

**Comment by mehdi-cit** [comment]
Hello again.
Just in case someone stumbles upon this thread. There's a nice library that could help with using tailwind:
https://dev.to/43081j/using-tailwind-at-run-time-with-web-components-47c
NB: _I have not tried it myself yet_

**Comment by erikkroes** [comment]
Hi Mehdi!
If you do happen to try it out, please share! We'd be more than happy to share your result. Odds are there are more people who can benefit from your work!

**Comment by mehdi-cit** [comment]
I will hopefully share here anything of interest. But I had to put my ambitions on ice as I'm extremely busy with other matters.
