### ISSUE TITLE
[textarea] CSS warnings

### ISSUE THREAD

**Issue by remcovaes** [ing-bank/lion#1252]
Steps to reproduce:
1. Open Firefox
2. Go to: https://lion-web-components.netlify.app/iframe.html?id=forms-textarea--main

## Expected behavior

No CSS warning

## Actual Behavior

2 warnings are shown:
`Error in parsing value for ‘max-height’.  Declaration dropped.`
[These lines seem to cause the warning](https://github.com/ing-bank/lion/blob/fa9cdffc8f4f2d65d395fd6c2e16e072a1eefa3b/packages/textarea/src/LionTextarea.js#L139)

`Ruleset ignored due to bad selector.`
Not sure were this is caused.

**Comment by jorenbroekema** [comment]
Just tested https://lion-web.netlify.app/iframe.html?id=forms-textarea--main in Firefox 72.0.2 64-bit on MacOS, and I cannot reproduce this.

Are you on windows by any chance?

**Comment by remcovaes** [comment]
I inittially reported it on windows. I just tried on a Mac Firefox version 86.0.1 and I also saw the warnings being present there. Make sure you have CSS warnings enabled in the console. 
![image](https://user-images.githubusercontent.com/20537012/110913537-973f6c00-8315-11eb-8df2-97698ac62cb2.png)

**Comment by tlouisse** [comment]
I think most of this is related to our docs page css: 
<img width="1076" alt="Screenshot 2021-03-22 at 12 06 12" src="https://user-images.githubusercontent.com/13814138/111981077-78a45680-8b07-11eb-8ad2-deac5b36f8dd.png">


Maybe the max-height is caused by https://github.com/ing-bank/lion/blob/master/packages/textarea/src/LionTextarea.js#L144 

For now, this has not a high prio for us.
Any help or contributions are always welcome of course :)

**Comment by tlouisse** [comment]
There was a bad line in FormControlMixin thats is fixed, thanks for pointing that out :)
The rest would need to be fixed mainly in Rocket: https://github.com/modernweb-dev/rocket
