### ISSUE TITLE
Typing errors with `lion-select` for `modelValue` & `model-value-changed`

### ISSUE THREAD

**Issue by abdonrd** [ing-bank/lion#1372]
## Expected behavior

No typing errors.

## Actual Behavior

I just found a few typing errors with `lion-select` for the `modelValue` property and for the `model-value-changed` event:

<img width="586" alt="Screenshot 2021-05-07 at 19 21 15" src="https://user-images.githubusercontent.com/1007051/117532447-e0473000-afe7-11eb-833d-0542cfb07962.png">

<img width="639" alt="Screenshot 2021-05-07 at 19 21 32" src="https://user-images.githubusercontent.com/1007051/117532450-e3422080-afe7-11eb-818c-bc8a44c04053.png">

**Comment by jorenbroekema** [comment]
With a fresh Typescript project scaffolded from `npm init @open-wc` and installing @lion/select, I don't get this problem and .modelValue works as intended, without lit-plugin errors or type errors. I also get the autocomplete. 

Maybe you can reproduce the problem in http://webcomponents.dev/?

**Comment by jorenbroekema** [comment]
Ah it's because of https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin I see now, so probably related to https://github.com/ing-bank/lion/issues/1373 since modelValue stems from FormatMixin lit static properties.

I'm gonna mark this as external, since I believe this more to be a fault of the analyzer not being able to analyze mixins. TSC for example can analyze it and with regards to our types, it does work. If something can be done on our side to help the WCA along on this, let us know!

**Comment by gerjanvangeest** [comment]
I don't see this typing error anymore.
