### ISSUE TITLE
[form] [proposal] exporting input-datepicker utils

### ISSUE THREAD

**Issue by vssn** [ing-bank/lion#138]
When writing tests on forms, interacting with various inputs is viable. While working with the input-datepicker I found these test utils very helpful and time saving: https://github.com/ing-bank/lion/blob/master/packages/input-datepicker/test/test-utils.js

**Exporting the test-utils**
Making the utils available for public usage would make testing some steps easier and time saving. Especially in this case, where one must understand which components play together, e.g. date input, calendar overlay, selecting days and months etc.

**Comment by bashmish** [comment]
Hey, I agree that would be useful. But it is an extra responsibility on us to keep APIs clean and stable, because once made public the interface should be ideally never changed, or changed very rarely. So I can't guarantee we'll expose them any time soon. Let's keep your feature request open for now.

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
we now do if appropriate export test-helpers 👍 
we moved some stuff around so I am not sure if the helper you wanted is part of it 😅

going to "close" this feature request - feel free to create another issue if more test helpers need exposing 🤗
