### ISSUE TITLE
[lion-select] modelValue and formattedValue are set incorrectly

### ISSUE THREAD

**Issue by maxevilmind** [ing-bank/lion#1384]
## Expected behavior:
I am using options inside `ing-select` like the following `<option .modelValue="${{ actionCode: 'X', typeCode: 'IDENTITYCARD' }}">Menu item title</option>`
And I expect model value of the `ing-select` to be `{ actionCode: 'some action code', typeCode: 'some type code' }` when it is selected.
## Actual behavior
`formattedValue` is same as `modelValue` of the `ing-select` and the value is going to be `Menu item title` for both.
If I am using `value` attribute as per documentation here https://lion-web.netlify.app/components/inputs/select/overview/#select-overview, it sets both `modelValue` and `formattedValue` to `"[object Object]"`.

In our development we rely on the fact that the `formattedValue` has "what we want to show to the user" and `modelValue` has "what we want to send to the backend". In this case it does not work and it is blocking our development rn 🙈

**Comment by maxevilmind** [comment]
UPD: I also tried using `value` attribute + custom formatter, but it leads to `formattedValue` being set to an empty string. It flashes with a proper value, but then sets to an empty string.

Also, code segment on the line `47` in `LionSelect.js` looks very suspicious to me as it has the following comment above:
`// FIXME: For some reason we have to override this FormatMixin getter/setter pair for the tests to pass`

**Comment by jorenbroekema** [comment]
Passing .modelValue to `<option>` doesn't do anything :\ and adding a formatter to it will also not work because the native `<option>` does not use the FormatMixin, so teh formatter would never be executed.

**Comment by maxevilmind** [comment]
I was adding a `.formatter` to the `lion-select` and not an option

**Comment by jorenbroekema** [comment]
If I understand you correctly, you want the user to see whatever you put inside `<option>` tag, which already works, but you want to pass to the database a more complex representation of the selected value.

This can be achieved like so:

```js
import { LionSelect } from '@lion/select';

class FooSelect extends LionSelect {
  serializer(v) {
    return this._inputNode.options[this._inputNode.options.selectedIndex].modelValue;
  }
}
customElements.define('foo-select', FooSelect);
```

This will serialize to serializedValue (the value meant to store to storage e.g. database) always by taking the selected `<option>` from the native select that it wraps, and taking the .modelValue prop of the <option>, but this prop can be any name of course since you can bind any property to any html element at any given time.

Then since you serialize like that, it becomes a bit of a requirement to bind a modelValue prop to your `<option>` elements of your custom LionSelect extension:

```js
return html`
  <foo-select name="favoriteColor" label="Favorite color">
    <select slot="input">
      <option .modelValue="${{ value: 'Red', foo: 'bar-red' }}">Red</option>
      <option .modelValue="${{ value: 'Hotpink', foo: 'bar-hotpink' }}">Hotpink</option>
      <option .modelValue="${{ value: 'foo', foo: 'bar-blue' }}">Blue</option>
    </select>
  </foo-select>
`;
```

And now you can always do:

```js
mySelect.serializedValue; // e.g. `{ value: 'Red', foo: 'bar-red' }`
```

**Comment by maxevilmind** [comment]
@jorenbroekema  So are you saying that if I need to achieve `<option value="2">1</option>` and have `2` as a `modelValue` of `lion-select` and `1` displayed in UI I will need to extend the component?

**Comment by jorenbroekema** [comment]
No not really, the value attribute of the option, when selected, equals the modelValue of the select itself. However, you can't put complex javascript values as attributes, so if you need more complex representations you will either have to stringify them in the attribute and parse them in your select modelValue before passing them elsewhere, or you extend and do it like I outlined.

**Comment by maxevilmind** [comment]
@jorenbroekema ok, but even if I put it as simple as that `2` and `1` like in this example `<option value="2">1</option>`. `lion-select` will have `.formattedValue` equal to `2` which is not right. It should be `1`.

**Comment by jorenbroekema** [comment]
Actually it's the other way around. The formattedValue should indeed be 1 but that is based on the innerText of the option element. 

With all lion fields, the formattedValue is based on the modelValue, which for lion-select is `2`, so then a formattedValue of `2` makes sense. Lion select is special however, because the value shown to the user is based on the innerText of the selected `<option>`. So we need to add a special little something to correct that I believe. Will label it as a bug for now.

**Comment by jorenbroekema** [comment]
Okay so the reason this is rough is because formattedValue is hard coupled to `value` attribute of the native field, but select happens to be "odd" in that it does not actually render this value attribute to the end user, but rather renders the innerText. 

So technically speaking, formattedValue being equal to the `value` attribute of the native field is correct, and not a bug, however, we say that formattedValue is the value that is displayed to the user.... So we'll have to do some pretty tricky overrides of the FormatMixin to make that happen without bugs.

Failing test:

```js
it('sets the values correctly based on the option value and view value', async () => {
  const lionSelect = await fixture(html`
    <lion-select label="Foo item">
      <select slot="input">
        <option value="nr1">Item 1</option>
        <option value="nr2">Item 2</option>
      </select>
    </lion-select>
  `);
  expect(lionSelect.modelValue).to.equal('nr1');
  expect(lionSelect.serializedValue).to.equal('nr1');
  expect(lionSelect.formattedValue).to.equal('Item 1');
});
```

FormatMixin is quite tricky and I doubt this can be solved quickly, so I would imagine this could take a while to get solved.

@tlouisse  thoughts?

**Comment by maxevilmind** [comment]
@jorenbroekema thanks for reacting so quickly to this issue, I hope it will get picked up quickly too.
I would love to contribute, but I am afraid it might take a lot of time considering that I know very little about FormatMixin and high code standards of this repo, probably will be a lot of feedback

**Comment by maxevilmind** [comment]
@jorenbroekema @tlouisse any progress on this?

**Comment by Sreeragkv** [comment]
@jorenbroekema @tlouisse any progress?
