### ISSUE TITLE
parseDate() returns undefined with valid dates, depending on time & timezone

### ISSUE THREAD

**Issue by nathangray** [ing-bank/lion#1478]
## Expected behavior

Using locale format "year-month-day", if I call parseDate("2021/09/01"), it should return a Date, that is more or less equal to "2021-09-01"

import { formatDate, parseDate } from '@lion/localize';

console.log(parseDate("2021/09/01"));

`Tue Aug 31 2021 18:00:00 GMT-0600 (Mountain Daylight Time)`

## Actual Behavior

I get undefined

## Additional context

I'm trying this in the afternoon, in Mountain Daylight Time (UTC -6) so when the test is done, UTC time is a different day from local time. 

https://github.com/ing-bank/lion/blob/master/packages/localize/src/date/parseDate.js#L66
I think what is happening is due to my timezone, when the date is checked in line 66 there is a difference in date between local and UTC.  
Unfortunately changing that check to parsedDate.getUTCDate() and parsedDate.getUTCMonth() causes the tests to fail, and I'm not sure how to deal with that or if this is the correct solution.

**Comment by mauricioaraldi** [comment]
I also am facing this issue. Any timezone that has a negative timezone will actually break, based on the [line](https://github.com/ing-bank/lion/blob/5d30258dd6d16bf8c777841509037aed284bc8c5/packages/ui/components/localize/src/date/parseDate.js#L66) that you sent , because the parsed date will be one day less than the original string date.
