### ISSUE TITLE
Cannot find name 'EventHandlerNonNull' when using open-wc starter with @lion/core and typescript

### ISSUE THREAD

**Issue by NingenJanai** [ing-bank/lion#1507]
## Expected behavior

Build and start without errors
```

import { LitElement, html, css } from '@lion/core'
import { customElement } from "lit/decorators.js";

@customElement('my-component')
export class MyComponent extends LitElement {
    static styles = css`
        :host {
            background-color: red;
        }
        `;

        render() {
            return html`<slot></slot>`;
        }
}

declare global {
    interface HTMLElementTagNameMap {
        'my-component': MyComponent
    }
}
```

## Actual Behavior
```

npm run start

> open-wc-lion@0.0.0 start D:\Projects\open-wc-lion
> tsc && concurrently -k -r "tsc --watch --preserveWatchOutput" "wds"

node_modules/@lion/core/src/DelegateMixin.d.ts:11:14 - error TS2304: Cannot find name 'EventHandlerNonNull'.

11     handler: EventHandlerNonNull;
```

**Comment by jorenbroekema** [comment]
You're probably using a different typescript version than we are, we're still on `3.9.7`. 
We should definitely upgrade to latest, but there's a 100 or so type issues to solve if we try that, although that's already better than the thousands we had for earlier versions of v4 when that was still very buggy.... which is why we fixed the TS version to v3.9.7

Typescript tends to do breaking changes whenever, so yeah kinda tough..  But for this type error it's a pretty easy fix, so I created a PR for that so at least maybe you can continue. Be aware though, you may run into other issues so then downgrading your own typescript to 3.9.7 can fix that in the meantime, until we're on latest.
