### ISSUE TITLE
@lion/switch triggers [focused-visible] on mouse events

### ISSUE THREAD

**Issue by gvonkoss** [ing-bank/lion#1517]
## Expected behavior

The `[focused-visible]` attribute to show up on the component when it has a keyboard-based interaction

## Actual Behavior

`[focused-visible]` is triggered by a mouse interaction with the component, as well.

Visit the [`lion-switch` code example from the documentation](https://lion-web.netlify.app/simulator/#?story-file=https%3A%2F%2Flion-web.netlify.app%2F67ec8768.js&story-key=main&theme=light&platform=web&language=en-US&edge-distance=true), inspect the element and click to see the attribute toggle.

https://user-images.githubusercontent.com/16777943/138711294-3593c700-650a-45ee-9ae5-98ef4604f32f.mov

## Additional context

Using `@lion/switch` v0.18.0

**Comment by tlouisse** [comment]
> Ok ended up going down a bit of a rabbit hole, but...

Thanks for trying this out 💪 
Yesterday I also investigated a bit to get a better grip on the issue.
The problem was indeed that a click triggered an extra toggle, because a label click already triggered a toggle and now you got two that canceled out each other. This could be solved by removing the toggle on label click (https://github.com/ing-bank/lion/blob/master/packages/switch/src/LionSwitch.js#L86), but the result was the same a for using `.focus()` (see below).

Am I right the issue can be defined as:

_**Once the switch has gotten state `[focused-visible]`, and it lost its focus to a non focusable element (like document.body), it unrightfully gets `[focused-visible]` again once the label of the switch is clicked the next time**_

The gif below illustrates this (yellow bg means `[focused-visible]`, blue border means `[focused]`):

![switch_focusedVisible](https://user-images.githubusercontent.com/13814138/139532414-ad045c59-1813-498b-bae2-1b7332725c48.gif)





(If you want to replicate this css + html was applied):

```html
<style>
[focused],
.btn:focus {
  border: 2px solid blue;
}

[focused-visible],
.btn:focus-visible {
  background: yellow;
}
</style>

<label for="b">Label</label>
<button id="b" class="btn">bla</button><br/>
<label for="i">Label</label>
<input id="i" class="btn">
```


Conclusion: it only happens in a certain edge case I think, but I wouldn't know yet how to solve this...

**Comment by gvonkoss** [comment]
That's such an odd edge case. I can't seem to replicate the change in focus to the body—it looks more like it will drop the `[focused-visible]` if any _focusable_ element is focused on (before or after the switch receives focus) 🤯 

([it's living here with your styles kinda](https://codesandbox.io/s/romantic-currying-umpvi))

https://user-images.githubusercontent.com/16777943/139847376-9debeea4-a928-4677-84cd-f9f30f23df9f.mov


https://user-images.githubusercontent.com/16777943/139847381-fa037a5a-6a4e-4e60-9568-bb4653eca144.mov




And about the issue definition : it seems that it would be more accurate to say when it loses its focus to a _focusable_ element, but it changes the state permanently to the expected behaviour.

> Once the switch has gotten state [focused-visible], and it lost its focus to a non focusable element (like document.body), it unrightfully gets [focused-visible] again once the label of the switch is clicked the next time

**Comment by tlouisse** [comment]
Ah, right, so it's even more complicated. When two lion-switches are used it does indeed unrightfully get focused-visible when coming from a focusable element as well... 

Also from document.body as you can see in my third gif, so the definition would be:

**Once the switch has gotten state [focused-visible], and it lost its focus, in some cases it unrightfully gets [focused-visible] again once the label of the switch is clicked the next time**

I agree 🤯 is the only applicable emoticon here.

Maybe the best way to get a grip on the issue is to slowly build it up with a minimum of platform elements and see what happens:

```html
<label for="b" @click="${({target}) => target.nextElementSibling.focus()}"></label><button id="b" class="input-node"></button>
```
