### ISSUE TITLE
[Feature request][combo box]: always let the modelValue reflect the value of the text box

### ISSUE THREAD

**Issue by M49A2** [ing-bank/lion#1664]
Currently when you just type in some free text (without selecting anything in the list with suggestions), the modelValue will always be empty. Also no model-value-changed event will be thrown when typing. The only way to get the modelValue updated is by selecting a suggestion.

I would like to have the current text box value available as modelValue and also want/need to listen for model-value-changed events when the user starts typing.

**Comment by tlouisse** [comment]
Thanks for the request. This definitely makes sense for a search input, where the text box is leading.
Currently, in the combobiox the listbox is leading. This however also has its usecases, so I think the 'fallback' to modelValue *(which basically makes the text box leading) should be a configurable option on top 👍 
It's been a while since I worked on the code, but I hope it would be conceptually smth like:

```js
get modelValue() {
  const listboxVal = super.modelValue;
  // TODO: come up with flag name less horrible than allowNonPredeterminedValues
  if (!listboxVal && this.allowNonPredeterminedValues) {
    return this._inputNode.value;
  }
  return listboxVal;
}

```

Question would be how to do this when `multiple` flag is enabled as well

**Comment by gerjanvangeest** [comment]
@M49A2 This is fixed in mentioned PR.
