### ISSUE TITLE
[icon] throws when svg is null

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#185]
If you change the svg property on `lion-icon` to null, it throws an error. This is because there is only a check for undefined here: https://github.com/ing-bank/lion/blob/master/packages/icon/src/LionIcon.js#L86

You can see this by setting `svg` to `null` in the demo.

**Comment by bashmish** [comment]
Can we think in advance about all possible values that should be handled correctly by `<lion-icon .svg>`? Ideally we need to prevent creating issues (this and [that](https://github.com/ing-bank/lion/issues/115)) for each case when someone uses a non-expected svg type.

I don't think it is a good idea to program in a defensive style, and now we are kinda doing that and start to check for each wrong value. Maybe we should turn it around and just say: everything that is a valid value will be rendered, and everything else will be ignored and nothing will be render.

On the other hand, my original thinking was that people do want the component to throw if they pass a wrong value to it, because why wouldn't it, it helps to prevent errors, because most likely this is an error. I'm not sure now if my thinking was correct or not.

What do you think? Can we just let the component to ignore all values except the right ones? Or you think `undefined` and `null` checks will be fine, and everything else should throw (like `{}`, `true`, `false`, whatever...)?

**Comment by LarsDenBakker** [comment]
I agree it's good to throw on invalid input, like `{}` or `true`. I'd say undefined and null or indications that you don't want to render something, so it's good to handle them equally. I wish javascript just had one nullish value...

**Comment by bashmish** [comment]
@LarsDenBakker can you implement a MR for this?

**Comment by jorenbroekema** [comment]
Should be fixed in https://github.com/ing-bank/lion/pull/276
