### ISSUE TITLE
[calendar] Disabled dates get skipped by keyboard

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#194]
When a calendar has disabled dates and a user navigates by keyboard, these dates get skipped. This is logical behaviour if we would see the calendar as just a set of buttons. Usually interactive elements that are disabled can't be navigated to.

In a calendar however, what we are mainly navigating is not the buttons, but the grid of dates. The buttons just happen to be in those cells. There is value in the coherence and structure of the grid, and being able to browse these disabled dates. 

For example, a screen reader user goes through a calendar. They would like to select a Monday, but for several weeks, all Mondays are unavailable. In the current pattern, they would have to use right or left arrow and go through all weekdays before they find a Monday. If the disabled dates were navigable, they would be able to use the down and up arrow to go through just the Mondays. 

I would suggest changing the keyboard navigation to include disabled buttons. For added convenience, I would suggest prepending something like "Unavailable, " to the accessible name of these dates.

**Comment by ovidiu1** [comment]
#468

**Comment by daKmoR** [comment]
As we are using native buttons and native buttons can not be focused if they are disabled we basically "can not" do this...

If we need a possibility to focus disable dates then these dates should NOT be buttons... we could make a fake `div` button - however, I assume this will have other a11y implications?

anyone else see a better solution?

**Comment by daKmoR** [comment]
sooo we had a few discussion around this - quite complicated 🙈 

it all starts with that having focusable disabled native browser buttons is impossible.
Spec Highlight: `disabled controls are entirely non-interactive`
Spec Paragraph:

> The difference between disabled and readonly is that read-only controls are still focusable, so the user can still select the text and interact with it, whereas disabled controls are entirely non-interactive. (For this reason, only text controls can be made read-only: it wouldn't make sense for checkboxes or buttons, for instances.)

https://www.w3.org/TR/html50/forms.html#attr-input-readonly

Therefore we need to tackle this in a different way 🙈 

We think this is the most promising solution
- Use a `div` with role=“button“ instead of a native button
- Use `disabled` attribute for styling
- Use `aria-disabled` for screen readers
- Manage click/enter/space from within the Calendar

**Comment by daKmoR** [comment]
an example in react with lots of divs 🤣
http://react-day-picker.js.org/examples/disabled-interaction/
