### ISSUE TITLE
[LionInputDatepicker] does not work on Firefox

### ISSUE THREAD

**Issue by Sciurus7** [ing-bank/lion#1962]
## Reproduction recipe
- Open https://lion-web.netlify.app/components/input-datepicker/overview/ adn set the overview to inline
- Open the calendar
- Click on one of the day buttons, either using the mouse or keyboard.

## Expected behavior

The current selected date changes

## Actual Behavior

Nothing happens

## Additional context

LionInputDatepicker @lion/ui: v0.2.0
Firefox v111.0.1

## Cause
From what I can find the event target of the click event in the calendar becomes the datepicker component itself instead of the day button. Therefore no date change is triggered. See [__clickDateDelegation](https://github.com/ing-bank/lion/blob/593d3301588b6b1ac9e4b58de22a4a3fc259b7c6/packages/ui/components/calendar/src/LionCalendar.js#L756) for the problematic code.

## Potential solution
Move the click listener to the day buttons.

**Comment by riovir** [comment]
Currently, we can't go to production with this component in our Design System because of this issue. I'm happy to work on a PR to remedy it, but could certainly use some pointers, especially on what really is the difference between Firefox and the rest of the browsers with event propagation with the following circumstances:
- event travels across two layers of shadow DOM
- there is a native Dialog element in the middle of the DOM element chain
- it's not just a mouse thing, space and enter keys are also blocked
- however, if I programmatically dispatch a `new Event('click', { bubbles: true, composed: true })` from the calendar day button element, suddenly the component behaves as expected. That tells me that the click event, be that via mouse, touch, or keyboard is not coming from the button
