### ISSUE TITLE
Incredible amount of releases!

### ISSUE THREAD

**Issue by MateWW** [ing-bank/lion#197]
Hello,
Is there any reason why there is close to 1000 releases?
It's really weird there is less then 250 commits and close to 1000 releases.
I was really flabbergasted when i get in home page.
Do you think about any limitation of it?

TODO:
- [x] Ignore changes to non-production files (fixed in #212)
- [ ] Only release `feat` and `fix` commits

**Comment by bashmish** [comment]
I share your concern, but let me explain how we ended up here.

We want:
- continuous deployment
- monorepo with independent versioning
- conventional changelog support

We managed to setup `lerna` with `yarn workspaces` to implement those requirements and make scripts work reliably. That came with a cost of having many releases, sometimes with just simple version bumps and no real code changes.

Now we have some ideas about how to decrease the number of releases:

1. do not release if merged commits were all of type `chore`
    I saw people using `chore` and making refactoring of the code, that is not right, because refactoring of the production code must be released. Misuse of `chore` should be avoided so that we can introduce this fix.

2. do not release if a component didn't have any code changes and only had some dependencies updates with no breaking changes
    If I'm not mistaken it was hard to implement due to some weird behavior or inflexibility of `lerna`. We can investigate it further and maybe find a way to fix that, maybe we'll have to fix smth for `lerna` itself first. Maybe @daKmoR remembers why it was not possible?

3. use `develop` branch to accumulate multiple changes, or basically merge to master less often
    I would rather avoid this, because this is not how I understand continuous deployment. At the same time for some closely related changes, e.g. if someone works on a feature and needs to implement some fixes and do some refactorings related to it, we can use a temporary branch to accumulate changes related to it and release them all together. We do this sometimes.

Any other thoughts?

**Comment by bashmish** [comment]
The only [easy improvement](https://github.com/ing-bank/lion/pull/212) we could introduce is ignoring the changes to test and documentation related files.

Strategy 2 is impossible because of [how lerna works with semver](https://github.com/lerna/lerna/issues/1907#issuecomment-461983745).

Strategy 1 I believe is still possible, but requires either an extra feature for lerna to add a filter for non important commits or an extra layer on top of lerna which will reimplement parts of its functionality, e.g. do the analysis of the commits between the current master state and last release state and run `lerna publish` only if important commits were added. Not so trivial.

Strategy 3 does not require any immediate changes, it is more about the workflow, rather than code improvements. We will sue it where applicable.

**Comment by jorenbroekema** [comment]
Hmm so I recently looked at this and ran into the same 3 things... for now I think having a develop branch would be a good idea after we launch v1. During alpha I think it's okay to have lots of releases and just release very often. Once we are v1 I think we should use develop branch and do a bit more "scheduled" releases.

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
We are now using changeset + github actions... so we are closing this feature request
