### ISSUE TITLE
[proposal] Provide an online repo for isolating bugs 

### ISSUE THREAD

**Issue by mihaisavezi** [ing-bank/lion#219]
Either on stackblitz or codesandbox, can we add a working lion project, to be used as a starting point when someone wants to illustrate a bug ?

I've been trying to setup one from scratch, from a lit-element example, but we have dynamic imports in lion, and they are not supported by default. 

This is what I have for now, and it still throw errors. ```https://stackblitz.com/edit/lion-datepicker-bug?file=select-demo.js```

**Comment by tlouisse** [comment]
There was a mismatch in deps

Changing in this line in `package.json` makes it work:
```
    "@lion/select": "0.1.40",

```

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
a webcomponents.dev link with some working lion code is now part of our issue template.

thx for the suggestions - I am closing this feature request
