### ISSUE TITLE
[input-datepicker] Validation message not shown in prefilled datepicker

### ISSUE THREAD

**Issue by mihaisavezi** [ing-bank/lion#222]
### What is expected to happen:

1. If datepicker is prefilled and the data doesn't pass validation, validation message is shown even if the input hasn't been touched.

### What happens

1. If datepicker is prefilled and data doesn't pass validation, validation message is not shown.
2. Form recognizes the error state.

### Other details

What is odd is that the modelValue going through the validator changes. 
On first pass-through it is the pre-filled data, but on the next pass-throughs the modelValue = the current day.

https://codesandbox.io/s/thirsty-butterfly-tkek2

**Comment by tlouisse** [comment]
Thanks for the report 👍 

I forked it and added some more debug info: https://codesandbox.io/s/compassionate-hugle-epw2p

What you see here is that the input-datepicker is not considered `prefilled`, but the regular input works fine. 

The cause is the computation of `prefilled` for Date values in `InteractionStateMixin`:

I guess adding this would solve it (lin 62, InteractionStateMixin), but I didn't try it yet:

```js
f (typeof value === 'object' && value !== null && !(value instanceof Date)) {
```

The main problem is that we don't have 'SpecSuite' anymore, which made it possible to run all mixin tests (InteractionStateMixin in this case) for an extending element (input-datepicker in this case).
I will try to look into reintroducing this SpecSuite functionality to cover for those cases in the future.

I probably will only have time to look into this next week, but a merge request is always welcome :)
