### ISSUE TITLE
[proposal] detect all form integration issues

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#237]
## Problem
We get many (unnecessary) bug reports. A lot of them are caused by a lack of integration tests within our own system.
A small difference in a sub class can have a big impact and can go undetected. 
#### Examples:
- [a different modelValue type](https://github.com/ing-bank/lion/issues/222) 
- a sub class that 'competes' with the `FormatMixin`: https://github.com/ing-bank/lion/blob/1ba4cd4a6d37a90c91283a2e0639ca6858d93ede/packages/field/src/LionField.js#L152 

## Solution
For a stable, maintainable core, we can test the integration between super class (usually a mixin like `InteractionStateMixin`) and sub class (usually a web component like `lion-field` or `lion-input`).

#### An example that already does this
See: https://github.com/ing-bank/lion/blob/master/packages/input-datepicker/test/lion-input-datepicker-integrations.test.js
With this code we were able to detect the fact that the `InteractionStateMixin` doesn't integrate correctly with modelValues of type 'Date'.

Similarly, we could have detected the second example of the problem statement above(causing unpredictable formatting behavior for all input subclasses) by running the test suite of `FormatMixin` for `LionField`: this would have prevented several bug reports on our extending layers.

## Extendable concept
It is vital that we run these integration at least for our form core (`packages/field`) mixins,
but this concept is applicable to every extension (run the `lion-field` tests on `lion-input`, run the `lion-input-date` tests on `lion-input-datepicker` etc. etc.).

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
sort of like a duplicate...

"closing" this feature request in favor of https://github.com/ing-bank/lion/issues/373
