### ISSUE TITLE
[lion-form]/[lion-button] Button declared outside lion-form doesn't trigger validation in the form

### ISSUE THREAD

**Issue by mihaisavezi** [ing-bank/lion#274]
## Context

In our app we have a form defined in a dialog template. And we have actions on those buttons, which check the form for errors. When I click the button and the form is in a invalid state.

Select a date in the past, then try clicking the button 'click from outside lion-form', 

## Expected

The form will show the validation messages.

## Current behaviour

If the lion-button is defined in a lion-form, this behaviour occurs. If the lion-button is defined outside of the form, this behaviour does not occur. Check example

Example repo: https://codesandbox.io/s/bug-lion-web-form-feedback-971bp

**Comment by mihaisavezi** [comment]
I'm guessing, it's because the button defined inside the form is expected to work like a submit button. Correct ?

**Comment by jorenbroekema** [comment]
From what I know, native buttons are by default type="submit". I would expect lion-button to work the same way. If you want a button inside a form to not submit the form, you would put type="button". 

Buttons outside the form have no knowledge of which form to submit, so they don't cause a form submit.

Is this in line with the behaviour that you're getting? Because then I think it is fully intended.

**Comment by tlouisse** [comment]
What Joren says is correct. 

I think the best solution is to add a click listener to your button, which calls `myLionFormReference.submit()`

Side nopte: the platform has the ability to do `<button form="myFormId">`, but we don't support this for now. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by gerjanvangeest** [comment]
Since you gave a 👍. I'm closing this issue, please reopen if you still have questions.
