### ISSUE TITLE
Fieldset children are not registered in formElements.

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#306]
In the case of such a code snippet:

```
export class Question extends IngFieldset {
  ...
  render() {
    return html`
      <lion-radio-group name="question-group" id="question-group"
        ><lion-radio
          name="response[]"
          id="response_yes"
          label="Yes"
          choiceValue="true"
        ></lion-radio>
        <lion-radio
          name="response[]"
          id="response_no"
          label="No"
          choiceValue="false"
        ></lion-radio>
      </lion-radio-group>
    `;
  }
}
```

`lion-radio-group` is not automatically registered as `formElement`, also `validation-done` of `lion-radio-group` is not propagated to Question component.

For this to work I have override the following functions.
```
  _dispatchRegistration() {
    let group = this.$id('question-group');
    group.addEventListener('validation-done', ev => {
      this.__validate(ev);
    });
    group.errorValidators = [['required']];
    this.dispatchEvent(
      new CustomEvent('form-element-register', {
        detail: {element: group},
        bubbles: true
      })
    );

    super._dispatchRegistration();
  }
  _unregisterFormElement() {
    super._unregisterFormElement();
    this.removeFormElement(this.$id('question-group'));
  }
```
I don't know if this is a good approach? and Is this a bug or feature?

**Comment by gerjanvangeest** [comment]
My first quess is that the `radio-group` ends up in the `shadow DOM`, which causes it not to be registered. I don't see any objections against your approach, but to be sure its best to test it fully in a form on multiple browsers.

**Comment by lfusiara** [comment]
Will you support components in `shadow DOM`?

**Comment by gerjanvangeest** [comment]
I tested it fully, and it seems to work, except you need to use `inputGroupTemplate()` instead of the `render()`, to get the fieldsets label, helptext etc.

Documentation on how to do this in a correct way is still missing, and maybe the functions you override need to changed into public functions. So I'll add a `enhancement` label to this issue.

**Comment by lfusiara** [comment]
Thanks, I will verify it

**Comment by lfusiara** [comment]
Unfortunately, this does not solve the problem, the `question-group` component is still not registered in `formElement` - component validation and serialization do not work.

The only change is the appearance of label helptext etc. as you wrote

**Comment by gerjanvangeest** [comment]
I created a branch to demo it: https://github.com/ing-bank/lion/tree/demo/question-component/packages/question

In the storybook you can see `validation` and `serialisation` working.

**Comment by lfusiara** [comment]
It is working because you add my function `_dispatch Registration`. But it should work out of the box without any additional registrations.

Without this functionality, custom components cannot be used inside lion forms

**Comment by jorenbroekema** [comment]
Hmmm might be some misunderstanding here. We purposely ensure our form elements are in lightDOM, otherwise it's really difficult to support accessibility. Currently we simply don't support form elements in ShadowDOM because of this.

For you, I think the right fix is to specify the renderRoot to be lightDOM (this).
https://lit-element.polymer-project.org/guide/templates#renderroot you can find detailed information for that here.

We should probably include in our documentation more clearly that if you want to encapsulate logic by means of a webcomponent, which has form elements inside of the template, you have to render to LightDOM for the form elements to work with the form (form & form elements must be in the same DOM). 

Let us know if this works for you!
