### ISSUE TITLE
[LionField]: initial .modelValue is not being formatted on first render

### ISSUE THREAD

**Issue by jdevega** [ing-bank/lion#327]
When using lion-input-amount and setting .formatOptions attribute on it, the first render does not apply this format options to the value but it does when the value is changed.

```html
<lion-input-amount
  label="Amount"
  help-text="Pre-filled and formatted value input"
  .modelValue=${20}
  .formatOptions=${{ 
    minimumFractionDigits: 0, 
    maximumFractionDigits: 0
  }}>
</lion-input-amount>
```

![image](https://user-images.githubusercontent.com/1290752/66806255-6643e780-ef27-11e9-8975-31d3e1f115a7.png)

**Comment by gerjanvangeest** [comment]
I can confirm this bug, do you see time to fix it in a pull request?

**Comment by daKmoR** [comment]
yeah that's a pretty annoying one 🙈 

Make sure to set the modelValue last as otherwise formatOptions will not be taken into account when running the formatter 👍 

added a demo for this usecase
https://lion-web-components.netlify.com/?path=/story/forms-input-amount--show-no-fractions

PS: we are on the underlying problem "member order independence" but for now this is what you need to do 😅
