### ISSUE TITLE
[OverlayMixin] Shadow outlet slot wrapper breaks content slot

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#382]
## Describe the bug

The problem is https://github.com/ing-bank/lion/blob/master/packages/overlays/src/OverlayMixin.js#L120

It adds a wrapper in between the host element and the content node. The content node happens to be a slot (slot="content") of the host element, and should always be a direct child. Due to us adding a wrapper in between, the content slot is no longer a direct child of its host element, and slots are not spec'd to be that way.

DOM:
<img width="405" alt="Screenshot 2019-11-15 at 14 14 04" src="https://user-images.githubusercontent.com/36734656/68946664-d0b0a780-07b3-11ea-95ca-d66920e0b93b.png">

https://www.w3.org/TR/dom41/#finding-slots-and-slotables  --> see second point "Let shadow be slotable’s parent’s shadow root.". If the slotable's parent is not the host element, it won't have a shadow root nor a shadow.

https://github.com/ing-bank/lion/pull/383/ I introduced some FIXME's related to using querySelector for slots instead of only checking direct children in this PR so please resolve those once this is fixed :).

**Comment by jorenbroekema** [comment]
Soooo.. 

Basically, the slottable DOM element gets moved to the global root node when it's a global overlay. This means that the slot no longer works, for example you could try to style the slottable with the :slotted CSS selector from the ShadowDOM, but since the slottable element is now gone from the host element, it wouldn't work.

The problem is not the outlet. The problem I think is that we still have the slot attribute on the outlet and the content after it's moved away from the host scope. So we should be transparent here by removing the slot attribute --> it doesn't work anyway 🤷‍♂ and that's normal because we're moving LightDOM (with slottables in it) around, which we can't really avoid for global overlays to work properly.

@tlouisse  Maybe you can give your 2 cents here, I'm tempted to actually remove the bug label because it's not a "bug", but we should clarify / clean it up.

**Comment by tlouisse** [comment]
Yeah indeed, the element with **[slot="content"]**  will be moved into **[slot="_overlay-shadow-outlet"]** and therefore the shadowRoot of your host element will not regard **[slot="content"]** as a slot anymore after moving.

Functionally this is not a problem, unless you want to style the element **[slot="content"]** from your host, which I agree we should support...

So it should be possible to put `._contentNodeWrapper`/ **[slot="_overlay-shadow-outlet"]** in the shadow root.

The implementing party (the one that uses `OverlayMixin` and creates the shadowRoot)  should probably add `<div id="myContentNodeWrapper"><slot name="content"></slot></div>`.
Then you could provide the wrapper to the OverlayController like `contentNodeWrapper: this.shadowRoot.querySelector('#myContentNodeWrapper')`

An alternative (maybe easier) solution would be to have `.contentNode` as the element provided to Popper (aka: omit the `._contentNodeWrapper` for local overlays). 
However, when using a tail/arrow this is going to be problematic again, since the tail/arrow will need to be a child of `.contentNode` then (Popper requires this if I'm right?) and then we have the styling problem again, since it wouldn't be 

So I would opt for putting `._contentNodeWrapper` inside the shadow root, allowing us to fully style both the **[slot=content]** and **[slot=arrow]**

**Comment by jorenbroekema** [comment]
FYI The arrow problem I solved by not using slot for it but just creating a webcomponent with a placement prop that sync with the x-placement attr of the popper element.

But yeah seems to me there is no harm in having the wrapper in shadow dom so that the content node is again a direct slot child (and stylable with slotted)

**Comment by jorenbroekema** [comment]
Fixed here https://github.com/ing-bank/lion/pull/695
