### ISSUE TITLE
getCurrencyName gives back wrong values in IE

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#402]
When we use 'getCurrencyName' in IE, it returns different values than other browsers.

so: `getCurrencyName('USD', { locale: 'en-GB' })` returns 'USD', whereas it should return 'US dollars'.

This is probably because Intl.NumberFormat doesn't return the right info in IE

**Comment by wsloth** [comment]
Looked at this a little bit, but I'm guessing this issue occurs depending on which `Intl` polyfill the host application is loading. I'm not sure whether this is an issue for Lion itself, or whether we should code to work around it if the polyfill has a bug. What do you think?

**Comment by tlouisse** [comment]
@wsloth In most cases, we compensate for Intl differences in the platform. For instance: https://github.com/ing-bank/lion/blob/master/packages/localize/src/number/normalizeIntl.js

Wrt the polyfill: I think it is caused by the platform and not the polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
(IE supports Intl).

Although compensating for this particular IE bug would not be a trivial task. It would require loading a huge list of data with entries like 'US dollars', and then for every currency+locale combination.

Maybe it is actually an idea to force a polyfill for IE.
Then we should first test if it is solved by loading a polyfill and then we can document which ones are recommended and should be loaded by the application developer

**Comment by jorenbroekema** [comment]
```js
Intl.NumberFormat('en-GB', { style: 'currency', currency: 'USD', currencyDisplay: 'name' }).format(500);
```

Gives back `500.00 US dollars` in chrome but `USD 500.00` in IE11. 

This is simply browser inconsistency. The only way for us to fix that is to load something that, as Thijs mentioned, has all the data in all the different locales for the currency display of all currencies. That's going to be really expensive, whether it's a polyfill or library. 

For me this goes into the category "wontfix coz IE11 sux", since I can't think of a feasible/acceptable fix, and it's not that breaking for IE11 users. They should be "used to it", since all other websites that use Intl (which most do) will also have this issue.
