### ISSUE TITLE
[proposal] consider human readable changelogs

### ISSUE THREAD

**Issue by tmsns** [ing-bank/lion#430]
Currently, the `CHANGELOG.md` files are listings of git commits in the current package, albeit with less integrated information (no users, no status of CI, ..):
* https://github.com/ing-bank/lion/blob/master/packages/core/CHANGELOG.md
vs
* https://github.com/ing-bank/lion/commits/master/packages/core

The proposal would be to adhere to more human readable changelogs instead of just using commit messages. As the project is adhering to conventional commits, commit messages explain **_what_** they change, but not **_why_** and what the consequences are. Human readable changelogs will help users identify the impact and reason of the release without having to go into the commits and check every file. 

Both [lit-html](https://github.com/Polymer/lit-html/blob/master/CHANGELOG.md) and [LitElement](https://github.com/Polymer/lit-element/blob/master/CHANGELOG.md) adhere to this standard [Keep a changelog](https://keepachangelog.com/). The monorepo of [Material Web Components](https://github.com/material-components/material-components-web-components/blob/master/CHANGELOG.md) as well. They maintain only one changelog for the complete project. They also maintain a version of the complete monorepo, in lerna, not package.json. This means that every package is still separately released. These package releases could still reference the commit logs accessible in GitHub or on the command line.

This might somewhat impact or be impacted by the proposal of #414 where nightly releases are discussed.

Let me know what you think. 😃

**Comment by jorenbroekema** [comment]
I like the idea of having a more human readable changelog, and perhaps we have arrived now at a point where it may be worth the maintenance, since our user base / contributor base has increased with the announcement of lion.

The problem I see however is that we don't have a changelog for our monorepo as whole, because we don't have a single version that all packages are aligned on. 

Considering our issues with circle dependencies however where we now have a script to validate versions of our internal packages, and extension layers need to ensure the versions are "aligned" otherwise they get multiple custom element defines... I feel like it may be worth it for us to go the MWC way, where all packages are the same version, and we can maintain a monolithic changelog that is human readable. Question is, what do we do with the package-specific changelogs? Keep them robotic and auto-generated as they are now?

One argument against this approach is in the concept of continuous integration. Every PR merged to master releases the package if a source file is in the diff. This means every source code change that gets merged is immediately released, which is great. If we go the monolith release route however, it will not be continuous integration, but rather "scheduled" or "on-demand". I think I'd personally be in favor of making that sacrifice, if what we get is better monolith changelog for our users and no more circle dependency bugs and error-prone version management.

**Comment by jorenbroekema** [comment]
Closing as enhancement with votes needed. Note: I am gonna actually look into migrating to changesets (from lerna) which provides a way to create human readable changelogs, because they don't take the commit message like lerna/standard-version does :)

**Comment by tmsns** [comment]
Nice, looking forward to it! 😊

**Comment by tmsns** [comment]
@AymenBenAmor might be something nice to look into, “changesets” that is. 😊

**Comment by daKmoR** [comment]
we moved to changeset so this is now officially closed
