### ISSUE TITLE
[calendar-feature] navigate to a specific day from another year.

### ISSUE THREAD

**Issue by ovidiu1** [ing-bank/lion#551]
## Navigate to a specific day from another year

If the user want to select a day from another year, he have to click on the previous/next month arrow until he get the year he need.  
I propose to develop a drop down in the header and let the user select the year he need it. 
 
The workflow should be like : 
 1. User select the year from the header. 
 2. After he select the year, all the days cells should be replace with the months acronyms.
 3. User click a month acronym he need it.
 4. After he click on month  acronym, the days cells should be replace with the days from the year selected on the first step.

**Comment by jorenbroekema** [comment]
Hmm I think for lion the minimum you need is navigatible months in order for the calendar to be somewhat functional. Having the year is optional, and open for extension layers to decide on how to do. I think if we put a year navigation on the calendar, it will only make it harder for extension layers to override the behavior that we put in place. For months we do it, again, because it's the minimum to have a functional calendar.

By the way, on our extension layer internally in ING, we will indeed have a year navigation above the months one, so that's on the way :). Hit me up on Mattermost if you're curious about timelines on that.

**Comment by jorenbroekema** [comment]
I'm putting wontfix for now as I don't think we will implement this on lion for the reason I pointed out. But I'll keep this open in case someone wants to discuss more first.

**Comment by jorenbroekema** [comment]
Inactive for a week so will close this now
