### ISSUE TITLE
[lion-radio-group] can't get keyboard focus when untouched/not prefilled

### ISSUE THREAD

**Issue by gerjanvangeest** [ing-bank/lion#569]
## Describe the bug

When a `radio-group` is untouched/ not prefilled it can't receive keyboard focus.

## To Reproduce

Try to focus via keyboard the `radio-group` in the first story:

https://lion-web-components.netlify.com/?path=/docs/forms-radio-group--default-story

Once an option is checked it can receive focus.

## Additional context

It looks like this behaviour appears since the latest `modelValue/name` refactoring

**Comment by tlouisse** [comment]
I think this s not a bug, but a flaw in our docs (after we moved to Storybook docs mode). Since all demos have the name `dinos`, the platform combines them into one single group.
The second demo has the checked value and therefore interacts with tab.

See a small simulation here: https://jsfiddle.net/pqt2hdam/2/ 
Tabstop 2 can only be reached once you set a checked value there.

**Solution**
Give all radio groups in our demos a unique name.
