### ISSUE TITLE
`this.children` not available for typescript compiler

### ISSUE THREAD

**Issue by jdvivar** [ing-bank/lion#576]
## Describe the bug

Typescript compiler doesn't recognise `this.children`

## To Reproduce

Check out this simple repo https://github.com/jdvivar/demo-bug-children-lion
Run `npm run compile`

### This is the failing code
```js
import {
  html,
  LitElement,
  TemplateResult,
} from '@lion/core'

export class DemoChildren extends LitElement {

  render (): TemplateResult {
    return html`
        ${[...this.children]}
    `
  }
}
```

### This is the non-failing code
```js
import {
  html,
  LitElement,
  TemplateResult,
} from 'lit-element'

export class DemoChildren extends LitElement {

  render (): TemplateResult {
    return html`
        ${[...this.children]}
    `
  }
}
```

## Expected behaviour

Both `demo-children-*.ts` files should be equally compiled by Typescript with no errors

## Actual behaviour

```
$ npm run compile

[11:10:10 AM] File change detected. Starting incremental compilation...

demo-children-lion-core.ts:11:20 - error TS2339: Property 'children' does not exist on type 'DemoChildren'.

11         ${[...this.children]}
                      ~~~~~~~~

[11:10:10 AM] Found 1 error. Watching for file changes.
```

## Additional comments
Note I'm not declaring the `lit-element` as a dependency in `package.json`. This is done on purpose so I can be sure the package loaded is the exactly the one declared as a dependency from and used by `@lion/core`

**Comment by jdvivar** [comment]
I've come to the conclusion it's probably a Typescript bug instead, however I'll keep it open in case someone can give me a hint about why exactly this is happening. Although I suspect it's just Typescript messing around with typings.

**Comment by jdvivar** [comment]
OK, I tried with Typescript 3.7.2 and 3.7.5, but at least I can confirm this is solved in `next`. I guess it's a freshly fixed bug. Closing as it's solved!

**Comment by jdvivar** [comment]
Making a copy of `@lion/core/index.js` into `@lion/core/index.ts` makes it work 🤔

**Comment by jorenbroekema** [comment]
My suspicion is that because we re-export LitElement without exporting the type (we don't export types anywhere in lion currently), the compiler doesn't understand that LitElement extends HTMLElement and has the children property.

That would also explain why making a copy of the index.js makes it work, because then you have the context of the re-export, so then when you import, the TS compiler can actually trace that it comes from lit-element and that it extends HTMLElement.

**Comment by jdvivar** [comment]
@jorenbroekema Thanks for your comment. 2 not-very-elegant solutions I found for now:

1. A first obvious solution is using `@ts-ignore` since this is really something I can't fix. However, most linters have a rule that disallows its use, which I agree with by the way.
2. Using `super.children` instead. From a purist point of view, this makes little sense, however it gives the right output with no warning.

It's also important to note that I only received that error if I extend `LitElement` directely. When I extend from class mixins instead, as in:
```js
class NewClass extends classMixin(LitElement) {
  // ...
}
```
then the ts compiler doesn't yell... which makes sense because it loses the trail of the class types and just allows anything I guess?

**Comment by jorenbroekema** [comment]
Types in combination with mixins as far as I know have always been tough. JSDocs I think still has issues with it, and I know Typescript had issues with it too in the past, not 100% sure if it's still troublesome. 

`super.children` is not a bad solution and probably the best thing for you at the moment, but it's a bit odd, usually the pattern is: if a child inherits a prop from parent, then within that child you access the prop from the child, 

We've had conversations in the team about exporting types for all exported things in our `index.js`s, and it's pretty clear that this is something we really want to do, but we haven't found the time for it yet due to other things getting higher priority.

I think exporting types in lion is something that people could probably contribute to the project though! Especially if there is someone out there who's way more into Typescript than we are. 

Might be an idea to start an issue for type exports, where you or someone else can propose an approach, and then if we're on the same page we'd be happy to accept a pull request for them 🤗

**Comment by jorenbroekema** [comment]
Reopening this btw, not having HTMLElement props recognized by TS on our LitElement re-export because we're missing types is definitely an "open issue" in my mind ;)

**Comment by jorenbroekema** [comment]
Should be fixed when we address https://github.com/ing-bank/lion/issues/82
