### ISSUE TITLE
[field] support pattern, min and max attribute?

### ISSUE THREAD

**Issue by miriamfranco** [ing-bank/lion#59]
Hi! Would be possible to support in lionfield, the attributes: pattern, min and max?
Thanks!

**Comment by bashmish** [comment]
Your question totally makes sense and in the beginning we considered such an API which basically mimics the native forms API. There are multiple reasons why we chose our own way instead of this:

1. Requirement to have different [types of validators (error, warning, info, success)](https://github.com/ing-bank/lion/blob/%40lion/validate%400.2.3/packages/validate/docs/ValidationSystem.md#types-of-validators)
2. Requirement to ensure an unambiguous order of validators (since this is an array, e.g. `errorValidators=${[validator1, validator2, ...]}`)
3. No global namespace pollution, statical analysis friendly => better scalability (since references are used instead of some global registry where all validators are registered and then used by name)

We sacrificed local DX though, but this is a trade-off.

For `min` and `max` please use one of [these validators](https://github.com/ing-bank/lion/blob/%40lion/validate%400.2.3/packages/validate/index.js#L20).

**Comment by bashmish** [comment]
For the `pattern` I created an additional [feature request here](https://github.com/ing-bank/lion/issues/63). Thanks for letting us know!

**Comment by miriamfranco** [comment]
Thanks for the response! In my case, I need the pattern because I need to show the numeric keyboard in iphone, and with the type=number only, doesn't work.
