### ISSUE TITLE
[dialog] You can still select elements behind the backdrop

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#614]
## Describe the bug

> The reason why I'm working on this is- in your example, it's easy to tab behind the modal backdrop. In Chrome, I select the URL bar, press tab, and I've got focus on the "Open" button.

So all this sort of work is an attempt to correctly model modality. Native <dialog> does this.

More details in this tweet
https://twitter.com/samthor/status/1233144739165196288?s=20

**Comment by LarsDenBakker** [comment]
The lion solution is definitely a collection of hacks (I wrote some of the initial stuff, I'm allowed to say it :) ). I saw the tweet too, it's definitely worth investigating. 

I'm surprised the open button can be selected from the URL bar, I'm pretty certain it wasn't like that before 😲 Also, we're using `inert` which is supported by chrome: https://caniuse.com/#feat=mdn-api_htmlelement_inert and should block focus on the button. That's even more surprising...

**Comment by tlouisse** [comment]
I think the keydown event is not fired when you 'tab into the window', so this method will not be handled: https://github.com/ing-bank/lion/blob/master/packages/overlays/src/utils/contain-focus.js#L92
We can probably detect this tab via `focusin` and restore the focus to the first focusable element in the dialog.

**Comment by LarsDenBakker** [comment]
Good catch! Then I guess it was always broken :(

**Comment by CITguy** [comment]
@LarsDenBakker, what are the metrics that you gauge accessibility against? 

------
(personal opinion below, please take with a grain of salt)

A component is not accessible unless techniques work for all major browsers (evergreen at minimum, but hopefully IE11, too).  Relying on functionality that isn't available across browsers would be an accessibility failure in my book (e.g., inert isn't available in Firefox or Safari).  Additionally, if you're only targeting the popular browser(s) (i.e., chromium-based) for accessibility/compatibility, then you have immediately failed because you are creating an exclusive solution that contradicts the inclusive-for-all definition of accessibility.

**Comment by LarsDenBakker** [comment]
My comment about inert was that I am surprised it's still a bug on chrome even though we use it. On other browsers we polyfill the behaviour, where I could understand bugs like this since it's a hacky solution.

**Comment by tlouisse** [comment]
I think the accessibility in our case is covered already by `aria-hidden=true`. @erikkroes usually does some elaborate a11y testing on our components, so I think it's quite safe to say that it is accessible (tested on Jaws, NVDA, VoiceOver).
Since the original issue was about the focus behind the backdrop, I will mark this issue as `bug`, so  someone can pick it up :)
