### ISSUE TITLE
[form] Support "pattern" validator

### ISSUE THREAD

**Issue by bashmish** [ing-bank/lion#63]
We need an alternative to `<input pattern="...">` in our form system.

**Comment by tlouisse** [comment]
You could currently implement it as a [Custom Validator](https://github.com/ing-bank/lion/blob/master/packages/validate/docs/tutorials/CustomValidatorsTutorial.md) that uses your regex under the hood.

Pattern basically is some kind of platform validator, but without a specific 'goal' in mind (the goal depends on what the Application Developer puts in the pattern attr).
All the platform validators we currently offer in Lion, have translations by default, so that they are accessible by default (not only the fact that they have messages, also the tone and 'clarity' of the message are checked for a11y).
Misha explained here very well why we prefer Lion Validator functions: https://github.com/ing-bank/lion/issues/59#issuecomment-495102815

It's highly recommended to use the default translations and for a possible PatternValidator we can't provide them.
In the future we want to make overriding and adding validation messages easier, and then we could consider the patternValidator. 
For now, I would create a [Custom Validator](https://github.com/ing-bank/lion/blob/master/packages/validate/docs/tutorials/CustomValidatorsTutorial.md)

**Comment by bashmish** [comment]
I have mixed feelings about this. To understand the problem this is good to illustrate this with an example (taken from MDN, actual code with Lion will differ):

![image](https://user-images.githubusercontent.com/137844/58243957-f3f12180-7d51-11e9-9298-4538f25564bc.png)

You specify a format in your input label (`Enter username (upper and lowercase letters)`). When the error message pops up you have an idea that you didn't follow the expected format which is `upper and lowercase letters`.

Then if you translate your application to multiple languages (what we support in Lion out of the box where possible), you need to translate this text `Enter username (upper and lowercase letters)` to multiple languages yourself, while the pattern validator error message (e.g. `Please match the requested format.`) will be translated by Lion automatically for you.

You can instead create [a custom validator](https://github.com/ing-bank/lion/blob/master/packages/validate/docs/tutorials/CustomValidatorsTutorial.md) and use it's API to provide a better UX with a good readable error message. Then the logic of patter matching will be in a custom validator function, the label will be `Enter username` (still needs to be translated to all languages) and the error message will be `Please only use upper and lowercase letters` (with all needed translations within a custom validator). The amount of work is actually more then, but we generally think that a better UX is worth it.

But I also see now that:
- if Lion users want to have a format in a label, they should be able to do so (and implement translations of the label only), it makes sense for non reusable pattern validators
- if Lion users create single language websites where they want to just specify a format in the label and rely on a generic error message in the pattern validator, this is also a valid use case

So for these Lion users it still makes sense to implement it.

**Comment by miriamfranco** [comment]
Thanks for the response! In my case, I need the pattern because I need to show the numeric keyboard in iphone, and with the type=number only, doesn't work.

**Comment by tlouisse** [comment]
Seems like a fair use case.
Currently exposing the props on the host wouldn't fit nicely on top of our validation api as @bashmish explained. 
It might be worth considering in the future to make the platform and our validation system play nicer together, or we could consider an option for triggering a certain keyboard.

For which type of input do you actually need them if I may ask? If it is for `input-iban` for instance, we can discuss with UX and enable this keyboard behavior by default.

For now (**_although not officially recommended and not guaranteed to not break in the future_**) you could do:
```js
LionInput.$$slot('input').pattern = ...
```

**Comment by tlouisse** [comment]
Closing this one. @miriamfranco please reopen when needed.
