### ISSUE TITLE
[dialog] close-overlay doesn't work from web component

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#631]
## Describe the bug

When you create a custom web component and load this in the content slot of a lion-dialog, the close-overlay event does not work. When you dispatch this, the dialog is not closed.

Dialog:
```
<lion-dialog .config=${{ hidesOnOutsideClick: true, hidesOnEsc: true }}>
    <button slot="invoker">Styled dialog</button>
    <styled-dialog-content slot="content"></styled-dialog-content>
</lion-dialog>
```

styled-dialog-content:
```
render() {
    return html`
      <div><p>First part nice looking dialog</p></div>
      <div><p>Look how nice this <span class="nice">dialog</span> looks!</p><p>This is also content.</p></div>
      <button
        class="close-button"
        @click=${e => e.target.dispatchEvent(new Event('close-overlay', { bubbles: true }))}
      >⨯
      </button>
    `;
  }
```

**Comment by jorenbroekema** [comment]
I assume this is because of the shadow boundary. There's two solutions:

1. Set the option `composed: true` next to the option `bubbles`, so it bubbles past shadow boundaries. A brute force solution that usually we would discourage.
3. Render to LightDOM with `createRenderRoot() { return this; }`, probably not what you want since you want encapsulated styling on your content.
3. Change the @click to not dispatch the event on the `<button>` (through `e.target.dispatchEvent`), but to dispatch it on the host element instead (which is not in the ShadowDOM) `this.dispatchEvent`. What you could do is set the event target to your `<button>` if you'd like to, but for me it makes sense that, since you're explicitly redispatching, the target should be your Web Component, which it is by default.

Let me know if that helps ;)!

**Comment by jorenbroekema** [comment]
Also, if you go for option 3 and it works perfectly, would maybe be nice to add a demo for it since using a web component for the content slot will be VERY common, because it will be the default way people will style content in their dialogs in an encapsulated way.

**Comment by jorenbroekema** [comment]
Now documented on how to get passed this :)
