### ISSUE TITLE
[lion-input] Feedback doesn´t update with clear method

### ISSUE THREAD

**Issue by carlosesteban55** [ing-bank/lion#648]
## Describe the bug

When I call LionField call() method from my custom input, the feedback for validation doesn´t update. I have a Maxlenght validator. If input hace feedback-for: error and i call clear method, the input clear well, but the validation stay with error when it´s false.

I think that solution is reset the modelValue, not only the value.

**LionField.js**
```
clear() {
    if (super.clear) {
      // Let validationMixin and interactionStateMixin clear their
      // invalid and dirty/touched states respectively
      super.clear();
    }
    this.value = ''; // can't set null here, because IE11 treats it as a string
    **this.modelValue='';//SOLUTION**
  }
```

## To Reproduce

1. Add a validator in the input like this,

<lion-input .validators=${[new MaxLength(5)]} label="Label" ></prisma-input>

2. Type 6 characters.
3. Now the feedback for attriebute has error case.
4. call clear() method of LionField class.
5. See that the "feedback for" continues with error.
6. It´s wrong because lenght=0.

## Expected behavior

feedback for attribute has empty value.

## Screenshots

![image](https://user-images.githubusercontent.com/49064780/76985272-42565900-6940-11ea-81ef-a054d714082e.png)

**Comment by jorenbroekema** [comment]
https://lion-web-components.netlify.com/?path=/story/forms-input--validation can be reproduced pretty easily here yep. 

Seems like clear only sets the viewValue (`value`) to '', if I switch it to `this.modelValue = '';`, it works.

Only one test fails if I change it:

The last expect fails
```js
it('can be cleared which erases value, validation and interaction states', async () => {
    const el = await fixture(html`<${tag} value="Some value from attribute">${inputSlot}</${tag}>`);
    el.clear();
    expect(el.value).to.equal('');
    el.value = 'Some value from property';
    expect(el.value).to.equal('Some value from property');
    el.clear();
    expect(el.value).to.equal('');
  });
```
because setting the value **property** imperatively like that doesn't change the modelValue, and then clearing the modelValue doesn't trigger a model-value-changed, which means it is not parsed and synced down back to `value`... Bit of a weird test really, as far as I know we shouldn't use `value` like that, at least not with our current codebase.

Does it make sense that clear function clears the modelValue? @tlouisse  thoughts?


@carlosesteban55 thanks for creating the issues, really helpful to get this feedback from people using our fields in different ways then we ourselves use them. It means that you will catch things that we don't :).

**Comment by carlosesteban55** [comment]
Any notice of this issue? Thanks

**Comment by jorenbroekema** [comment]
Ah thanks for the bump, I think we would accept a PR for a fix here to change LionField line 165 to use this.modelValue, and then for the test that fails, we can change it to modelValue.

Could you create a PR :)?

**Comment by carlosesteban55** [comment]
You think that is better change both lines? Or add reset model value as it:

`clear() {
    if (super.clear) {
      // Let validationMixin and interactionStateMixin clear their
      // invalid and dirty/touched states respectively
      super.clear();
    }
    this.modelValue = ''; //Add this lines instead remove the next line
    this.value = ''; // can't set null here, because IE11 treats it as a string
  }`

**Comment by jorenbroekema** [comment]
Fixed here I believe https://github.com/ing-bank/lion/pull/668 , let me know if it's still broken and we can reopen it ;). Thanks again for contributing a fix
