### ISSUE TITLE
Child dialogs not working

### ISSUE THREAD

**Issue by gerjanvangeest** [ing-bank/lion#676]
## Child dialogs do not work

The parent dialog opens as normal, but the child dialog (so a dialog inside the parent dialog) doesn't want to open.

```html
    <lion-dialog>
      <button slot="invoker">Open parent overlay</button>
      <div slot="content">
        Parent dialog
        <lion-dialog>
          <button slot="invoker">Open child overlay</button>
          <div slot="content">
              Child dialog
          </div>
        </lion-dialog>
      </div>
    </lion-dialog>
```

Broken in latest releases of dialog/overlay.
Still worked in version dialog 0.4.12 & overlay 0.12.7.

**Comment by T-Motion** [comment]
The invoker of the child dialog has two click events attached. _setupOpenCloseListeners in LionDialog is being called twice, so two events are attached. This is causing the __toggle function in LionDialog to be called twice. 
Not sure how to fix it though.

**Comment by jorenbroekema** [comment]
Might be related to my recent fix for dialogs being moved in the DOM and going through init - teardown cycle twice?  It may be worth parking this issue until we've gotten rid of the shadow overlay outlet that Aymen is working on 🙈 

Thanks for the investigation @T-Motion  really helps to know the root cause of the nested dialog not (visually) opening.

**Comment by jorenbroekema** [comment]
I realized that the shadow outlet stuff wasn't affecting anything about this issue. So I created a fix. I checked that it fixes things for both the current overlays/dialog, as well as on the shadow outlet branch
