### ISSUE TITLE
[localization] make validator messages externally overridable

### ISSUE THREAD

**Issue by RB-Develop** [ing-bank/lion#68]
Some of the default messages that are used by the validators do not work very well in all contexts. If you have a long label name for an input that is required you might get something such as 'Fill Do you already have an account? in.' Naturally, that is not desirable. 

Currently we work around this issue by providing a fixed message on the global scope (i.e. 'This field is required.'), but we would like to be able to override the message on a per-field basis, without wrapping the input element. 

Tried to have a look at implementing this myself, but I cannot see a proper way of doing this. Took a reasonably quick look at the validator mixin and the localization mixin. Any suggestions?

**Comment by tlouisse** [comment]
Currently you can do:
```js
<lion-input label="Heeft u al een rekening?" 
    .getFieldName="${() => 'rekeningnummer'}">
</lion-input>
```

It's not recommended to override generic messages on a per app basis, since the default ones have been checked for 'user friendliness'(accessible for a broad audience) and consistent feedback contributes to a consistent 'form experience' across apps.

Changing the subject can be done as described above (it has a default fallback to label text).

However, there will be (edge) cases where you still want to override the whole message. Making a user friendly API for this is still a future we want to provide in the future.

**Comment by RB-Develop** [comment]
Ah cool, I did not know this was possible. It will do the job for our case. I do think we will still run into some edge cases though, so that friendly API would be nice. Can have a look at it next week perhaps and see if I can come up with a suggestion.

**Comment by bashmish** [comment]
@RB-Develop looks like `Do you already have an account?` is not a field label, but rather a header above it, I would suggest to challenge UX and eventually make a simple label `Account number` and keep such long sentences outside of labels, this will improve both UX and A11Y, and doesn't force you to find workarounds like @tlouisse  suggested.

Feel free to reopen if you have further questions or run into edge cases. Thanks for you question!

**Comment by RB-Develop** [comment]
This still leaves the problem that the label will be capitalized in the error message. So it will say `Fill in an Account number`. Besides, I do not feel that an arbitrary technical limitation is a strong argument to challenge UX with.

We will be using the workaround for now. I will not put in time to come up with a suggestion for a public API right now as I get the impression that this feature is not wanted at the moment.

**Comment by bashmish** [comment]
@RB-Develop this is not an `arbitrary technical limitation`, we have UX and A11Y specialists which help us to design core reusable components in a certain way. And this is why we don't implement what you expect, so it is a good thing that you ran into this issue and asked a question, this is where we share the reason why certain constraints exist and suggest to challenge your UXer. I hope that explains our vision and way of working.

**Comment by tlouisse** [comment]
Probably `getFieldName` is not so much of a workaround, since you would need it quite often. 
We should probably better document this.

And I agree the capitalisation looks weird and maybe we should offer:
- the opportunity to configure whether the subject is preceded by 'a' or 'an' instead of 'a(n)'. We cannot automate this, especially not for all locales.

and/or consider: 

- quotes around the subject (in that case prefix 'a(n)' would not be required in the error message and capitalisation would be less of a problem)

**Comment by RB-Develop** [comment]
If the first letter of the word is made lowercase and the 'a' or 'an' is made configurable, I think we already gain quite a bit of flexibility. Putting quotes around the label also seems like a nice consideration as well. 

Looking forward to what you come up with. Let me know if I can help in any way.

**Comment by tlouisse** [comment]
> Let me know if I can help in any way.

Maybe you could propose to our UX team and depending on the outcome do a feature/merge request 👍
