### ISSUE TITLE
How to handle singletons

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#690]
By using scoped elements it is possible to use multiple variants of lion in an app, is there a plan on how to make this work for the singletons? 

Will they guard their side effects? Or defer to the first registered singleton?

**Comment by tlouisse** [comment]
Good that you bring this up. We just discussed this internally in the team last week. @daKmoR  has an idea to solve this via dependency injection. I hope we can get it on our backlog soon 🙂

**Comment by LarsDenBakker** [comment]
Dependency injection would work for components (though we need to make sure that spawning lots of events isn't a performance problem). But that doesn't solve it for regular code which uses singletons, and it doesn't prevent singletons from being loaded in the first place.

**Comment by tmsns** [comment]
Is the goal to make singletons work across version/instance (and thus actually create “globals”). 
If yes, what happens if the interface of that singleton/global changes? Should a new singleton/global be created in that case?

**Comment by jorenbroekema** [comment]
Also, what if you have a breaking change, e.g. the name of method `msg` changed to `message`. If you resolve to the latest version, you will need to proxy the breaking changes somehow.

You could have a singleton manager that does this, as well as control which version of the singleton to use, and prevent instantiating multiple instances of essentially the same singleton class?

**Comment by jorenbroekema** [comment]
Problems to solve:
- Multiple majors of singleton classes (possible with ScopedElementsMixin) could mean multiple instantiations of something that should only be instantiated once: localize, overlays, ajax, etc.
- Breaking changes between major versions of singletons need backwards/forwards compatibility
- App Developer currently has no control on how problem 1 and 2 are resolved

Possible solutions that need a proof of concept:
- Dependency Injection
- Singleton Manager (app level only, can never be more than 1, dont use scoped elements mixin to scope this)
- First singleton instance wins
- ... feel free to comment more ideas, I'll edit this comment to add them

**Comment by LarsDenBakker** [comment]
One other option is to separately publish singletons, and use package managers to installs single versions.

Also good to look at the requirements, you may not need each singleton to be an actual singleton. Maybe for some of them the behavior can be slightly adjusted to allow multiple versions, or behavior can be extracted.

**Comment by jorenbroekema** [comment]
I added some requirements for each of the packages that use singleton (I hope I didn't miss any).

**Comment by jorenbroekema** [comment]
Here's another scenario on the extension layer which to me seems problematic no matter the reason why something is a singleton:

Feature A on v1 consumes utils which are on v2.
Both feature A and utils use ajax singleton. Feature A has a unit test which stubs the get function of v1 ajax singleton, but the test fails now because the util using v2 don't use the same get function that Feature A stubs in its unit test.

**Comment by askbeka** [comment]
I was trying to solve this problem to while ago,  and have arrived at conclusion that DI is a way to go.    
But not by events, rather import-maps.  
Reason is that singletons by definition are stactic information, defined  once in a module. So module should be of a single version.

Events based DI is applicable on runtime dynamic use cases and hierarchical relationship
where you want real dynamic behavior based on external input. ex. Localisation. And even better if it was used eclusively for passing data (state), rather than behavior.

**Comment by LarsDenBakker** [comment]
I agree, import map based dependency injection is the best option. 

It puts some requirements on consumers, perhaps it could be paired with one or more other options.

**Comment by tmsns** [comment]
DI based on import maps is certainly an option. 😃 
In this case, the shared interface is much broader: the complete module definition. It means that the exports of the DI modules are not allowed to break over major versions, and thus ever.

ie. 
```javascript
// localize.js (v1)
export function msg(key){ ... }
```

```javascript
// localize.js (v2)
export async function msg(key){ ... }
```
This is not allowed, as DI would break usage of localize that expect v1. To make changes, it will mean that a new module should be created (with a new name):
```javascript
// localize-new.js
export async function msg(key){ ... }
```

Another point is that changing DI system (eg. breaking change in import maps spec) is also not allowed, without supporting the old one. 🙈 

How would the DI system be introduced? A separate package from open-wc?

**Comment by tlouisse** [comment]
Currently @dakmor and me are working on a poc for the problems mentioned in this issue.

 Nice overview of challenges we try to tackle @jorenbroekema and others.
 I think we can roughly divide them into two more generic challenges:

## Challenges

1. How can we **prevent functional conflicts** (like breaking overlays) between different (major) versions of singletons?

2. How can we allow parts of an application to have a different configuration for a singleton (like a **Context api/ Provider system**)? (This is not directly related to versioning)

  I will focus on the first one below. @dakmor is working on the second one.
 I spoke to @dakmor and @ruphin about the topic an we came to the points below (please correct me if needed)

## Preventing functional conflicts

  Goals:
- Prevent functional collisions between two major versions of a singleton.
- Allow (but not encourage) breaking changes in singletons over time

 Non Goals:
- Improve performance by sharing resources between two versions of a singleton

Assumptions:
- Two major versions of a singleton will only occur during migration phases. It is always the goal to move to latest major as quick as possible
- Applications don’t consume multiple minor versions of the same major

What follows from those assumptions: performance issues will be tackled by moving to latest.
Note that having multiple minors of a singleton would not break functionally with proposed solution below, but it is just a bad practice.

### Approach
 Collisions can be avoided by extracting (sharing) the ‘collision surface’.  We can do this by sharing a global storage. 
For now this will be window, we are investigating the possibility of putting it in a separate package.
 
> Putting it in a seperate package will only work if there is one version of this package in the whole app and now it seems that yarn installs multiple versions, even if they have the exact same version number (@dakmor has a post about this?)).

  On top: in general it would be good to have a slower lifecycle for the singletons(separately publishing like @LarsDenBakker mentioned), but we should allow for breaking changes at some point in time.   

### Open question
- How do we observe changes in the global storage? Do we fire events on the window?

### What does this mean for our current singletons? 
- `localize`: a shared storage of translation will actually lead to collisions(think of two versions trying to define validator translations on the same namespace), so we only want to share current locale
- `overlays`: blocked state, opened overlays etc. (like Joren described)
- `ajax`: interceptors?
- `snackbar`: message queue
- `icons`: nothing? 
- more...?

**Comment by LarsDenBakker** [comment]
Sounds like a great approach! 

Currently we are investigating approaches on how to manage singleton packages, and how to manage resolving only a single version per major version of a package (so not different minors/patches). The latter is much more complicated than the former. We can share the learning here as well for consumers of lion.

**Comment by daKmoR** [comment]
# Singleton Manager Rational

We have an app with 2 pages.

- page-a uses overlays 1.x
- page-b uses overlays 2.x (gets installed nested)

```txt
my-app (node_modules)
├── overlays (1.x)
├── page-a
│   └── page-a.js
└── page-b
    ├── node_modules
    │   └── overlays (2.x)
    └── page-b.js
```

The tough part in this case is the OverlaysManager within the overlays package as it needs to be a singleton.

It starts of simplified like this

```js
export class OverlaysManager {
  name = 'OverlayManager 1.x';
  blockBody = false;
  constructor() {
    this._setupBlocker();
  }
  _setupBlocker() {
    /* ... */
  }
  block() {
    this.blockBody = true; // ...
  }

  unBlock() {
    this.blockBody = false; // ...
  }
}
```
The breaking change in `OverlayManager` was renaming of 2 function (which has been deprecated before).

- `block()` => `blockingBody()`
- `unBlock()` => `unBlockingBody()`

knowing that we can create a Manager that is compatible with both via

```js
import { OverlaysManager } from 'overlays';

class CompatibleManager extends OverlaysManager {
  blockingBody() {
    this.block();
  }
  unBlockingBody() {
    this.unBlock();
  }
}
```

all that is left is a to "override" the default instance of the "users"

```js
import { singletonManager } from '@lion/singleton-manager';

const manager = new CompatibleManager();
singletonManager.set('overlays::index.js::1.x', compatibleManager);
singletonManager.set('overlays::index.js::2.x', compatibleManager);
// "overlays::index.js::1.x" is a "magic" string define by the package itself
```

For more details please see https://github.com/ing-bank/lion/pull/703

## Steps forward

We feel confident in this solution and are looking for feedback. If no blocker arise we will start implementing it on all singletons we have 👍

**Comment by LarsDenBakker** [comment]
👍 for me

**Comment by tmsns** [comment]
Some reflections:

- I think we're missing the implementation of singleton-manager in the PR 🙈 Would be great to see how you use the "magic strings".
- Should `singletonManager` only be used internally in lion?
- As `singletonManager` is a singleton, it shares state. How will this be achieved over multiple instances on one page? Is it in there we would use the "global storage" (as you mentioned before)?
- What if the `singletonManager` specification/implementation changes between major versions? (eg. the magic string changes of format) One of the goals was to:
  > Allow (but not encourage) breaking changes in singletons over time
- I don't understand the following statement:
  > npm is not meant to handle something like this... and it never will
  ```txt
  my-app
  ├─┬ feat-a@x
  │ └── foo@2.x
  ├─┬ feat-a@x
  │ └── foo@2.x
  └── foo@1.x
  ```
  Isn't that the core of npm and node_modules? To allow different versions in sub packages, if semver doesn't matches?

**Comment by daKmoR** [comment]
@tmsns indeed I forgot to update the gitignore as I use multiple `node_modules` folder to simulate the node resolution system. it's pushed now 👍

##  I think we're missing the implementation of singleton-manager in the PR 🙈 Would be great to see how you use the "magic strings".

for this POC the singleton manager is basically a `new Map()` https://github.com/ing-bank/lion/pull/703/files#diff-3b1727a5ef4471adac65d6341c96ece6
in a real implementation we will most likely add some sort of check so that you don't override specific "magic" strings.

A magic string is defined by the singleton instance itself
something like this
```js
export const overlays = singletonManager.get('overlays::index.js::1.x') || new OverlaysManager();
```
e.g. `overlays::index.js::1.x` would be the magic string you need to know in order to override this singleton (this magic string will be used by all 1.x versions of `overlays` for 2.x it will be `overlays::index.js::2.x` that way you can specifically target mayor versions of `overlays`

see full example https://github.com/ing-bank/lion/pull/703/files#diff-820fefbb6bd76a39e9a0d971c63efaa6

## Should `singletonManager` only be used internally in lion?

`singletonManager` can be used on the app level & by singleton implementors 

###  As `singletonManager` is a singleton, it shares state. How will this be achieved over multiple instances on one page? Is it in there we would use the "global storage" (as you mentioned before)?

`singleton-manager` will be a package which will always be released as version `1.x` hence it should always be correctly deduped

##  What if the `singletonManager` specification/implementation changes between major versions? (eg. the magic string changes of format) One of the goals was to:
  > Allow (but not encourage) breaking changes in singletons over time

`singletonManager` does not have any "shared" state... each singleton has it's own states

##  I don't understand the following statement:
>   > npm is not meant to handle something like this... and it never will
>   ```txt
>  my-app
>  ├─┬ feat-a@x
>  │ └── foo@2.x
>  ├─┬ feat-a@x
>  │ └── foo@2.x
>  └── foo@1.x
>  ```
>  Isn't that the core of npm and node_modules? To allow different versions in sub packages, if semver doesn't matches?

yes the example was that npm will always have multiple nested versions of 2.x in this example... in order to only have 1 version of 1.x and 2.x for production builds (e.g. to not ship 2.x multiple times) it will require a separate step..

Note: multiple versions of 2.x still work with this approach while developing but it will ship waaayyy more data (which you certainly don't want for production)

**Comment by tmsns** [comment]
Thanks for the clarifications!

The big takeaway is that `singletonManager` is a **separate package with its own versioning**, separate from the variants of lion (original problem stated by Lars).

As long as this package doesn't get duplicated in the app, we should be golden. As you mention releasing on `1.x` will definitely help here, as at least no breaking changes are (ought to be) introduced. Additionally, we should set the guideline to always use caret versioning when referencing the package, otherwise deduping might still fail. An alternative would be to user yarn's resolutions.
