### ISSUE TITLE
[lion-select] No way to pre-select options with duplicate values.

### ISSUE THREAD

**Issue by sammytapa** [ing-bank/lion#698]
## Describe the bug

No way to pre-select options with duplicate values.

## To Reproduce

```
<lion-select .modelValue=${'flower'}>
        <select slot="input">
          <option value="fruit">mango</option>
          <option value="flower">rose</option>
          <option value="fruit">pineapple</option>
          <option selected value="flower">lotus</option> // this should be the selected value
          <option value="flower">lily</option>
        </select>
</lion-select>
```

## Expected behavior

Must pre-select `lotus`.

## Actual behaviour

Pre-selects `rose`.
<img width="1676" alt="Screen Shot 2020-04-29 at 7 19 29 PM" src="https://user-images.githubusercontent.com/10500454/80590411-66807c00-8a4e-11ea-9955-9482dfbb6331.png">

**Comment by tlouisse** [comment]
@sammytapa I guess it's not really supported. 
Under the hood it syncs `<lion-select>.modelValue` to `<select>.value` and it doesn't really look at the selected attribute of individual options. There's also the implicit assumption that one option maps to one option (instead of multiple).

Why would you want to create such a select (from a UX perspective)? It would be confusing for the user to see that different options of a select would submit the same end result?
I might be wrong, but I think the platform (talking about a bare select) is too forgiving here
