### ISSUE TITLE
Button has non-technical styling

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#70]
`lion-button` includes non-technical styling by default. This styling needs to then be overwritten by any design system implementing the button. This seems wasteful.

**Comment by bashmish** [comment]
Can you please give any specific example?

**Comment by LarsDenBakker** [comment]
When you visit https://lion-web-components.netlify.com/?path=/story/buttons-button--used-on-its-own you see that the button has visual styling which are not needed for the technical functioning of the button.

When extending I'd like to reuse the technical styles, but not the visual styles. Just separating them in two separates getters would be sufficient, but I thought the philosophy of lion was to only include technical styles in general.

We are extending `LionButton` here: https://github.com/open-material-components/open-material-components/blob/init/packages/button/src/OmcButton.js#L23 we ended up copy pasting the technical styles (40px height, hiding the slotted button, styling the click area etc.)

**Comment by bashmish** [comment]
@LarsDenBakker technical and A11Y styles (40px is a good example of those). Do you mean we should not change browser native look and feel of a button? I honestly don't see which particular properties you mean.

I also feel like it is a bad idea to extend styles. I would prefer to override them completely on the extension level, otherwise you'll have very very indirect style definitions on you extension layer and a huge coupling. Maybe it is not perfect, but more robust and readable. Exposing some reusable part of it as a style module seems like a good idea, but I'm not sure how much time we can invest into this.

**Comment by LarsDenBakker** [comment]
`LionButton` renders a button in the light dom, and adds a clickable area div which both require some specific css to make them work properly. 

I see your point about the coupling, perhaps then some default suggested css could be included in the documentation as it requires quite some specific knowledge to set it up properly.

**Comment by bashmish** [comment]
@LarsDenBakker can you create a small PR showing your vision on that? I do admit that this is smth we want in the long term, but for not this is not the highest prio, so code contributions are very welcome here :sun:

**Comment by tlouisse** [comment]
@bashmish : I think the button currently has a great set of features:
- Is touch device friendly be default, while maintaining simple API/great DX
- Accessible fundament for every Design system
- Leverages the platform by reusing the native button, requiring only a minimal amount of logic from our side. We don’t need a huge amount of boilerplate like paper-button
- compatibility with native forms (there will be just no other way to do this for quite some time other than placing a native button (sr-only) in light dom)
- Can easily be extended for advanced styling scenarios:
    - Adding a material design ripple
    - Adding icon slots/ other slots. Without web component, api would be a set of classes -> suboptimal DX
- Native buttons can give quirks: we noticed in overlay system dimensions were not properly measured, unless certain style props were set. Also, you need to set `width:100%` to make it behave as a block element. Now the host element just behaves like a default block element (div). 

In terms of styling, I agree with @LarsDenBakker : much off the above functionality is implemented via technical/functional styles.
As a Subclasser, you should get them for free, without having to think about them. I bumped into the same issue in the listbox-invoker button and in my personal extension layer playground.
Also, they should be reflected in our unit tests (and I think they partly already are).
If a Subclasser with a bare `class MyButton extends LionButton` has already failing tests, would be weird…
Technical/functional styles are a thing, think of:
- ‘Pointer-events:none’ -> disable user interaction
- Sr-only styles -> invisible for user, not for screen reader
- Page flow style -> wouldn’t make sense if an overlay Subclasser needs to reapply positioning
- Etc.

By not inheriting those styles, our components become more like design pattern examples from which you can assemble your own, whereas our goal is to extend from them, apply a Design System and add (not reapply) functionality

I think our goal should be to be as close to (and at least as conservative as) the platform button as possible:
- Inline in page flow (inline-block)
- Subtle, easily overridable background colour 
- Subtle, easily overridable focus indicator 
- Allows tweaks on host level for all box properties and pseudo selectors

And because we are even more conservative, we don’t need to reset native button styles:
https://css-tricks.com/overriding-default-button-styles/

## Stackblitz example
Here I made a proposal for a style component that takes into account all or most of the above:
https://stackblitz.com/edit/button-wc-styles?file=index.ts

**Comment by LarsDenBakker** [comment]
@tlouisse yep I agree

**Comment by gerjanvangeest** [comment]
Solved in: https://github.com/ing-bank/lion/pull/204
