### ISSUE TITLE
[tabs] select a tab without focusing it

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#715]
I would like to select a tab without focusing it programmatically.

It's not possible due to this line:

https://github.com/ing-bank/lion/blob/0ff4199f1ff4dead0521019948c44d29cbd8a998/packages/tabs/src/LionTabs.js#L40

Could we have a method to select a tab without focusing it?

**Comment by gerjanvangeest** [comment]
Can I ask what the use case would be for this feature?

**Comment by MathieuPuech** [comment]
I don't know if it is a valid UX, but here it is: there is a list of items displayed in different tabs. Each tab show a different organization of items.
One of the tabs is items filtered by an input. When I type in this input, it change the current tab to the filtered tabs.

There is something similar in mdc-tab-bar, if you set the property focusOnActivate (default to true), it focus the tabs when activated (see [mdc-tab-bar documentation](https://material.io/develop/web/components/tabs/tab-bar/)).

**Comment by jorenbroekema** [comment]
Sounds pretty reasonable to me. I'm looking at the code now and it's not exactly trivial on how to do this through the selectedIndex property because it's a setter which doesn't accept params. 

I suppose you could do something like:
```js
tabs.preventFocusOnSelection = true;

// preventFocusOnSelection (by default false) will be considered
// in selectButton (__updateSelected can pass it on)
tabs.selectedIndex = 2;
// preventFocusOnSelection is toggled back to false at the end of the setter. 
// So you have to be specific if you want to prevent the focus, 
// every time you use the selectedIndex setter
```

I'll ask the team if they agree with this API / behaviour and then we'd definitely appreciate if you could do a PR to create this :).

**Comment by tlouisse** [comment]
Sounds very reasonable. Maybe `tabs.preventFocusOnSelection = true` should be the default behavior actually?
I think it should only set focus if selectedIndex changed as a consequence of user interaction

**Comment by daKmoR** [comment]
Generally it's a user action on the tab to change a tab right? there it makes sense to also do the focus...

so if it is a programmatic change then imho a function it the most appropriate way... so maybe something like this?

```js
tabs.setSelectedIndex(2, { focus: false });
```

**Comment by jorenbroekema** [comment]
Hmm but I don't really like having 2 APIs that do the same thing, because then:

```js
tabs.selectedIndex = 2;
tabs.setSelectedIndex(2, { focus: true });
```

would do the exact same thing :\ we could remove the setter since we're still in alpha for lion, but I know we have some users actively using tabs component right, like webcomponents.dev?

So then we need to be pretty clear about that it's breaking, and in our own extension layer provide backwards compatibility layer and deprecate `tabs.selectedIndex` setter

**Comment by tlouisse** [comment]
Maybe we can just keep track of user interactions that trigger `selectedIndex` inside the component.

This is how most native components work as well. Changing a value programatically from the outside shouldn't change your activeElement.

**Comment by MathieuPuech** [comment]
I agree with @tlouisse : for example a checkbox, when you change the checked property, the input is not checked but when you click on it, there is a focus and checked is changed. It's the same behavior for select, radio, etc.

**Comment by jorenbroekema** [comment]
That sounds good to me :) as well then

**Comment by tlouisse** [comment]
👍 In that case we can mark it as a bug, I think

**Comment by jorenbroekema** [comment]
Marked as bug now, @MathieuPuech are you up for contributing a PR for this? Otherwise we can also ask the community to take it up

**Comment by MathieuPuech** [comment]
> Marked as bug now, @MathieuPuech are you up for contributing a PR for this? Otherwise we can also ask the community to take it up

I will do a PR for this
