### ISSUE TITLE
Commonjs, ES and UMD modules building for lion components

### ISSUE THREAD

**Issue by rajkeshwar** [ing-bank/lion#75]
As per my knowledge about the libraries. It provides `Commonjs`, `es` and `umd` modules as output to consumed by projects. I don't see these modules in `lion`. The source files being scattered in root directory which `npm install lion` provides to consume. These modules are useful because it would be tested compiled and compressed. The `Commonjs` and `es` modules doesn't have any impact if the project uses any build script and does all building task. But `umd` modules gives ability to use the library through the browser and check any components without a build script. This is very useful when you want to show the example through `plunker` or `stackblitz`. 

I would like to configure the build script and would also like to organise the code for components being scatted at root level.

* **build:commonjs**: will build the CommonJS version in the **dist/lib** folder
* **build:es**: will build the ES2015+ modules version in the **dist/es** folder
* **build:umd**: will build the UMD version at **dist/umd/lion.js** (with sourcemaps)
* **build:umd:min**: will build the minified UMD version at **dist/umd/lion.min.js**

**Comment by bashmish** [comment]
Hey @rajkeshwar, the reason we don't provide the bundled/transpiled version of the code is because we believe it is not needed nowadays, because ES modules are available in all evergreen browsers. More than that, often people abuse bundled versions and include them instead of the source code.

I think the bundling is only an application concern now, rather than a library one, whereas Lion is a library.

> This is very useful when you want to show the example through plunker or stackblitz.

You can just use ES modules on websites like plunker with the help of [unpkg.com](https://unpkg.com), e.g.:

```js
import { LitElement, html, css } from 'https://unpkg.com/@lion/core?module';
``` 

If you want to use it in older browsers like IE11, you can use Stackblitz which will transpile everything automatically. For a working code you can take a look at [my example here](https://stackblitz.com/edit/js-ft652d).

**Comment by bashmish** [comment]
Feel free to reopen this if you have a good use case that we missed.
