### ISSUE TITLE
Use of Public Class Fields

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#923]
## Describe the bug

We use Public Class Fields here
https://github.com/ing-bank/lion/blob/master/packages/form-core/src/registration/FormRegisteringMixin.js#L20

They are a standard but are currently only available in chrome and firefox.

Using them can also lead to issues when the build is not taking this into account. So we either should not use them or make sure it's noted somewhere how to work with them.

Example Error in Webpack:

![Image Pasted at 2020-9-8 15-34](https://user-images.githubusercontent.com/24378/92485820-b38a1100-f1eb-11ea-85d6-afc63b492e29.png)

**Comment by vlaraort** [comment]
IMHO if this approach will cause fail builds in webpack, it should be avoided, because it implies a breaking change, as a consumer of the package will have to change their build configuration. Also, it will force consumers to have to transpile their dependencies code, causing a worse dev experience.

Anyway, what is the advantage of using it that way instead of using the designed lifecicle functions of litelement?

**Comment by daKmoR** [comment]
indeed, this was introduced by accident - we will revert the usage of Public Class Fields

**Comment by vlaraort** [comment]
Cool! 🥇
