### ISSUE TITLE
[Feature Request][Enhancement][Demo] Use github pages for demoing instead of netlify

### ISSUE THREAD

**Issue by fcarrascosa** [ing-bank/lion#938]
In order to keep all the information on the same place I think it would be cool if demo was shown on github pages instead of netlify which is the current way this repo is demoing its content. This comes with both, benefits and some cons.

## Benefits
- All the information regarding this repo is kept in the same place (github).
- Remove a dependency on a 3rd party provider.
- GitHub shows a nice link on the right bar to the "github pages" version of the repo.
- Can be deployed automatically on the release workflow (or any other) via github actions. 

## Cons
- The storybook build will be kept inside the repo (not a fan of having "compiled code" in a repo). Although there's the possibility to publish that result to a branch and use it as the source for github pages.
- Some modifications to the repo root directory should be included (github pages reads on either `.` or `docs` directory for its code).

**Comment by daKmoR** [comment]
hey there 👋

thank you for the suggestion however the con that we would have a "big" compiled blob that changes every time is kind of our main blocker for this.

The storybook "blob" is actually quite big (~7MB) and it will change almost with every commit/merge which would blow up our git repo size.
Therefore we prefer to push the code to a separate service. We might use a github action at some point to deploy instead of relying on netlifys build.

So we are not going to change - I hope this answers your question and our reasoning for it is clear.

If you have addition information please let us know 🤗

**Comment by fcarrascosa** [comment]
Clear!
Appreciate the response :D
