### ISSUE TITLE
[form][input] Reset not working after submitting invalid inputs

### ISSUE THREAD

**Issue by joanntaguinod** [ing-bank/lion#94]
## Steps to Replicate
1. Go to [form reset demo](https://lion-web-components.netlify.com/?path=/story/forms-form--form-submit-reset)
2. Enter invalid inputs for first name and last name
3. Click Submit button
4. Click Reset button

## Expected Behaviour 
Clicking reset button should empty the input elements

## Current Behaviour
Invalid input is retained in `value` propert.  However, when you inspect the `modelValue`, it is already cleared. Even if you manually delete the value, the element is putting it back.

**Comment by jorenbroekema** [comment]
Thanks for creating this issue!

I found some additional weird behavior on that demo:
1. Set input to some string (fewer than 15 char)
2. Press submit, looks fine.
3. Reset (does not work)
4. Press submit again (you suddenly get error message that you would normally get if the value was empty)

This seems to suggest that reset *does* clear the modelValue, but this is not synced back to the <input> viewValue. 

This bug may or may not be influenced by https://github.com/ing-bank/lion/pull/55 , so probably good to wait for this and check if it is still broken.

**Comment by bashmish** [comment]
I confirm this bug as well. Also when calling `querySelector('lion-form').reset()` or `querySelector('lion-form').resetGroup()`.

**Comment by tlouisse** [comment]
There is a fix in this branch: https://github.com/ing-bank/lion/compare/fix/formIssues
(ModelValue wasn't formatted, because we lately check for `errorState` as a condition for formatting. This check needs to be there only as user feedback(when typing in the field), not when modelValues are set  imperatively, like with the reset.)

Currently, there are more pending form bugs. When they are all solved and all individual fixes work together, this fix will be released

**Comment by joanntaguinod** [comment]
Is the demo using the latest release/master? I was still able to replicate the issue on the form reset story

**Comment by bashmish** [comment]
@joanntaguinod I checked on the Netlify and locally, and looks like the bug was fixed, but the storybook was not updated on the Netlify.

We are going to investigate what is going wrong with the Netlify storybook deployment.
