### ISSUE TITLE
[form/fieldset] Existing form elements being re-registered

### ISSUE THREAD

**Issue by dancarlocanlas** [ing-bank/lion#944]
## Expected behavior

Existing form elements should no longer be registered

## Actual Behavior

Certain form elements (datepicker in this example) is re-registered even if it's already exisiting, causing an error in the console

https://webcomponents.dev/edit/1Fk0J8Stvf3osr2UJgQl

## Additional context

- form: 0.6.23
- input: 0.9.2
- input-datepicker: 0.16.1

**Comment by daKmoR** [comment]
hey there 👋

so the issue is that lit-html is very smart when updating dom... e.g. it will reuse the existing dom node and only changes its data/properties... this however can lead to issues as lifecycle callback like connected/disconnectedCallbacks are not called in this case.

Therefore in your case, you should replace the `map` 
```js
          ${this.data.map((item) => {
            const { type } = item;
            const functionName = this._getRenderFunction(type);

            return this[functionName] ? this[functionName](item) : nothing;
          })}
```

with the [repeat directive](https://lit-html.polymer-project.org/guide/writing-templates#repeating-templates-with-the-repeat-directive)

```js
          ${repeat(
            this.data,
            (item) => item.id,
            (item) => {
              const { type } = item;
              const functionName = this._getRenderFunction(type);

              return this[functionName] ? this[functionName](item) : nothing;
            }
          )}
```

That way as long as the `item.id` is unique it will correctly replace full dom nodes. (e.g. make sure that each data entry has a unique id so no reuse of "startDate" for example)


I updated the code on webcomponent.dev and it seems to work fine 💪
https://webcomponents.dev/edit/u89yIv7ikOP1J9PZDFAn
